// ============================================
// MOCK DATA - Sistem HRM Perusahaan
// ============================================

// Employees List
export interface Employee {
  id: string;
  nama: string;
  jenisKelamin: "Laki-laki" | "Perempuan";
  agama: "Islam" | "Kristen" | "Katolik" | "Hindu" | "Buddha" | "Konghucu";
  status: "Aktif" | "Tidak Aktif" | "Cuti";
  noKtp: string;
  tempatLahir: string;
  tanggalLahir: string;
  alamatKtp: string;
  alamatDomisili: string;
  noTelp: string;
  tanggalBergabung: string;
  jabatan: string;
  statusPernikahan: "Belum Menikah" | "Menikah" | "Cerai";
  namaPasangan: string | null;
  jumlahAnak: number;
  fotoKtp: string | null;
  fotoDiri: string | null;
  noBpjsKesehatan: string | null;
  noBpjsKetenagakerjaan: string | null;
  fotoSim: string | null;
  noRekening: string;
  bank: string;
  namaRekening: string;
  kartuKeluarga: string | null;
  tanggalMulaiPkwt: string | null;
  tanggalBerakhirPkwt: string | null;
}

export const employees: Employee[] = [
  {
    id: "ID57201",
    nama: "Budi Santoso",
    jenisKelamin: "Laki-laki",
    agama: "Islam",
    status: "Aktif",
    noKtp: "3201011234560001",
    tempatLahir: "Jakarta",
    tanggalLahir: "1990-05-12",
    alamatKtp: "Jl. Merdeka No. 10, RT 03/RW 05, Menteng, Jakarta Pusat",
    alamatDomisili: "Jl. Sudirman No. 45, Apt. Tower A Lt. 12, Jakarta Selatan",
    noTelp: "0812-3456-7890",
    tanggalBergabung: "2021-03-15",
    jabatan: "Senior Software Engineer",
    statusPernikahan: "Menikah",
    namaPasangan: "Ratna Dewi",
    jumlahAnak: 2,
    fotoKtp: "/uploads/ktp-emp001.jpg",
    fotoDiri: "/uploads/foto-emp001.jpg",
    noBpjsKesehatan: "0001234567890",
    noBpjsKetenagakerjaan: "19005121990001",
    fotoSim: "/uploads/sim-emp001.jpg",
    noRekening: "1234567890",
    bank: "BCA",
    namaRekening: "Budi Santoso",
    kartuKeluarga: "/uploads/kk-emp001.jpg",
    tanggalMulaiPkwt: null,
    tanggalBerakhirPkwt: null,
  },
  {
    id: "ID57202",
    nama: "Siti Nurhaliza",
    jenisKelamin: "Perempuan",
    agama: "Islam",
    status: "Aktif",
    noKtp: "3201021234560002",
    tempatLahir: "Bandung",
    tanggalLahir: "1992-11-25",
    alamatKtp: "Jl. Asia Afrika No. 22, Bandung",
    alamatDomisili: "Jl. Gatot Subroto No. 88, Jakarta Selatan",
    noTelp: "0813-4567-8901",
    tanggalBergabung: "2020-07-01",
    jabatan: "Marketing Manager",
    statusPernikahan: "Menikah",
    namaPasangan: "Reza Firmansyah",
    jumlahAnak: 1,
    fotoKtp: "/uploads/ktp-emp002.jpg",
    fotoDiri: "/uploads/foto-emp002.jpg",
    noBpjsKesehatan: "0001234567891",
    noBpjsKetenagakerjaan: "19211251992002",
    fotoSim: null,
    noRekening: "2345678901",
    bank: "Mandiri",
    namaRekening: "Siti Nurhaliza",
    kartuKeluarga: "/uploads/kk-emp002.jpg",
    tanggalMulaiPkwt: null,
    tanggalBerakhirPkwt: null,
  },
  {
    id: "ID57203",
    nama: "Ahmad Fauzi",
    jenisKelamin: "Laki-laki",
    agama: "Islam",
    status: "Aktif",
    noKtp: "3201031234560003",
    tempatLahir: "Surabaya",
    tanggalLahir: "1995-08-03",
    alamatKtp: "Jl. Tunjungan No. 15, Surabaya",
    alamatDomisili: "Jl. Tunjungan No. 15, Surabaya",
    noTelp: "0814-5678-9012",
    tanggalBergabung: "2022-01-10",
    jabatan: "Sales Executive",
    statusPernikahan: "Belum Menikah",
    namaPasangan: null,
    jumlahAnak: 0,
    fotoKtp: "/uploads/ktp-emp003.jpg",
    fotoDiri: "/uploads/foto-emp003.jpg",
    noBpjsKesehatan: "0001234567892",
    noBpjsKetenagakerjaan: "19508031995003",
    fotoSim: "/uploads/sim-emp003.jpg",
    noRekening: "3456789012",
    bank: "BNI",
    namaRekening: "Ahmad Fauzi",
    kartuKeluarga: "/uploads/kk-emp003.jpg",
    tanggalMulaiPkwt: "2024-01-10",
    tanggalBerakhirPkwt: "2025-01-10",
  },
  {
    id: "ID57204",
    nama: "Dewi Lestari",
    jenisKelamin: "Perempuan",
    agama: "Hindu",
    status: "Aktif",
    noKtp: "3201041234560004",
    tempatLahir: "Yogyakarta",
    tanggalLahir: "1993-02-14",
    alamatKtp: "Jl. Malioboro No. 30, Yogyakarta",
    alamatDomisili: "Jl. Kemang Raya No. 12, Jakarta Selatan",
    noTelp: "0815-6789-0123",
    tanggalBergabung: "2021-09-20",
    jabatan: "HR Specialist",
    statusPernikahan: "Menikah",
    namaPasangan: "Arif Wicaksono",
    jumlahAnak: 1,
    fotoKtp: "/uploads/ktp-emp004.jpg",
    fotoDiri: "/uploads/foto-emp004.jpg",
    noBpjsKesehatan: "0001234567893",
    noBpjsKetenagakerjaan: "19302141993004",
    fotoSim: null,
    noRekening: "4567890123",
    bank: "BRI",
    namaRekening: "Dewi Lestari",
    kartuKeluarga: "/uploads/kk-emp004.jpg",
    tanggalMulaiPkwt: null,
    tanggalBerakhirPkwt: null,
  },
  {
    id: "ID57205",
    nama: "Rizky Pratama",
    jenisKelamin: "Laki-laki",
    agama: "Islam",
    status: "Aktif",
    noKtp: "3201051234560005",
    tempatLahir: "Semarang",
    tanggalLahir: "1997-07-20",
    alamatKtp: "Jl. Pandanaran No. 8, Semarang",
    alamatDomisili: "Jl. TB Simatupang No. 99, Jakarta Selatan",
    noTelp: "0816-7890-1234",
    tanggalBergabung: "2023-02-14",
    jabatan: "Frontend Developer",
    statusPernikahan: "Belum Menikah",
    namaPasangan: null,
    jumlahAnak: 0,
    fotoKtp: "/uploads/ktp-emp005.jpg",
    fotoDiri: "/uploads/foto-emp005.jpg",
    noBpjsKesehatan: "0001234567894",
    noBpjsKetenagakerjaan: "19707201997005",
    fotoSim: "/uploads/sim-emp005.jpg",
    noRekening: "5678901234",
    bank: "BCA",
    namaRekening: "Rizky Pratama",
    kartuKeluarga: null,
    tanggalMulaiPkwt: "2024-02-14",
    tanggalBerakhirPkwt: "2025-02-14",
  },
  {
    id: "ID57206",
    nama: "Maya Anggraini",
    jenisKelamin: "Perempuan",
    agama: "Kristen",
    status: "Aktif",
    noKtp: "3201061234560006",
    tempatLahir: "Medan",
    tanggalLahir: "1994-12-01",
    alamatKtp: "Jl. Imam Bonjol No. 5, Medan",
    alamatDomisili: "Jl. Rasuna Said No. 22, Jakarta Selatan",
    noTelp: "0817-8901-2345",
    tanggalBergabung: "2022-06-01",
    jabatan: "Financial Analyst",
    statusPernikahan: "Belum Menikah",
    namaPasangan: null,
    jumlahAnak: 0,
    fotoKtp: "/uploads/ktp-emp006.jpg",
    fotoDiri: "/uploads/foto-emp006.jpg",
    noBpjsKesehatan: "0001234567895",
    noBpjsKetenagakerjaan: "19412011994006",
    fotoSim: null,
    noRekening: "6789012345",
    bank: "Mandiri",
    namaRekening: "Maya Anggraini",
    kartuKeluarga: "/uploads/kk-emp006.jpg",
    tanggalMulaiPkwt: "2024-06-01",
    tanggalBerakhirPkwt: "2025-06-01",
  },
  {
    id: "ID57207",
    nama: "Hendra Wijaya",
    jenisKelamin: "Laki-laki",
    agama: "Buddha",
    status: "Aktif",
    noKtp: "3201071234560007",
    tempatLahir: "Makassar",
    tanggalLahir: "1988-09-15",
    alamatKtp: "Jl. Somba Opu No. 18, Makassar",
    alamatDomisili: "Jl. Kuningan No. 33, Jakarta Selatan",
    noTelp: "0818-9012-3456",
    tanggalBergabung: "2019-11-05",
    jabatan: "Operations Manager",
    statusPernikahan: "Menikah",
    namaPasangan: "Linda Permata",
    jumlahAnak: 3,
    fotoKtp: "/uploads/ktp-emp007.jpg",
    fotoDiri: "/uploads/foto-emp007.jpg",
    noBpjsKesehatan: "0001234567896",
    noBpjsKetenagakerjaan: "19809151988007",
    fotoSim: "/uploads/sim-emp007.jpg",
    noRekening: "7890123456",
    bank: "BCA",
    namaRekening: "Hendra Wijaya",
    kartuKeluarga: "/uploads/kk-emp007.jpg",
    tanggalMulaiPkwt: null,
    tanggalBerakhirPkwt: null,
  },
  {
    id: "ID57208",
    nama: "Putri Rahayu",
    jenisKelamin: "Perempuan",
    agama: "Hindu",
    status: "Cuti",
    noKtp: "3201081234560008",
    tempatLahir: "Denpasar",
    tanggalLahir: "1996-04-10",
    alamatKtp: "Jl. Sunset Road No. 7, Denpasar, Bali",
    alamatDomisili: "Jl. Senopati No. 55, Jakarta Selatan",
    noTelp: "0819-0123-4567",
    tanggalBergabung: "2022-08-15",
    jabatan: "UI/UX Designer",
    statusPernikahan: "Belum Menikah",
    namaPasangan: null,
    jumlahAnak: 0,
    fotoKtp: "/uploads/ktp-emp008.jpg",
    fotoDiri: "/uploads/foto-emp008.jpg",
    noBpjsKesehatan: "0001234567897",
    noBpjsKetenagakerjaan: "19604101996008",
    fotoSim: null,
    noRekening: "8901234567",
    bank: "BNI",
    namaRekening: "Putri Rahayu",
    kartuKeluarga: null,
    tanggalMulaiPkwt: "2024-08-15",
    tanggalBerakhirPkwt: "2025-08-15",
  },
  {
    id: "ID57209",
    nama: "Andi Setiawan",
    jenisKelamin: "Laki-laki",
    agama: "Islam",
    status: "Aktif",
    noKtp: "3201091234560009",
    tempatLahir: "Palembang",
    tanggalLahir: "1996-01-28",
    alamatKtp: "Jl. Jenderal Sudirman No. 40, Palembang",
    alamatDomisili: "Jl. Casablanca No. 18, Jakarta Selatan",
    noTelp: "0820-1234-5678",
    tanggalBergabung: "2023-04-01",
    jabatan: "Backend Developer",
    statusPernikahan: "Belum Menikah",
    namaPasangan: null,
    jumlahAnak: 0,
    fotoKtp: "/uploads/ktp-emp009.jpg",
    fotoDiri: "/uploads/foto-emp009.jpg",
    noBpjsKesehatan: "0001234567898",
    noBpjsKetenagakerjaan: "19601281996009",
    fotoSim: "/uploads/sim-emp009.jpg",
    noRekening: "9012345678",
    bank: "BRI",
    namaRekening: "Andi Setiawan",
    kartuKeluarga: "/uploads/kk-emp009.jpg",
    tanggalMulaiPkwt: "2024-04-01",
    tanggalBerakhirPkwt: "2025-04-01",
  },
  {
    id: "ID57210",
    nama: "Rina Wulandari",
    jenisKelamin: "Perempuan",
    agama: "Katolik",
    status: "Aktif",
    noKtp: "3201101234560010",
    tempatLahir: "Bogor",
    tanggalLahir: "1998-06-18",
    alamatKtp: "Jl. Pajajaran No. 25, Bogor",
    alamatDomisili: "Jl. Pajajaran No. 25, Bogor",
    noTelp: "0821-2345-6789",
    tanggalBergabung: "2023-01-20",
    jabatan: "Content Strategist",
    statusPernikahan: "Belum Menikah",
    namaPasangan: null,
    jumlahAnak: 0,
    fotoKtp: "/uploads/ktp-emp010.jpg",
    fotoDiri: "/uploads/foto-emp010.jpg",
    noBpjsKesehatan: "0001234567899",
    noBpjsKetenagakerjaan: null,
    fotoSim: null,
    noRekening: "0123456789",
    bank: "Mandiri",
    namaRekening: "Rina Wulandari",
    kartuKeluarga: null,
    tanggalMulaiPkwt: "2024-01-20",
    tanggalBerakhirPkwt: "2025-01-20",
  },
  {
    id: "ID57211",
    nama: "Fajar Nugroho",
    jenisKelamin: "Laki-laki",
    agama: "Islam",
    status: "Aktif",
    noKtp: "3201111234560011",
    tempatLahir: "Solo",
    tanggalLahir: "1991-03-22",
    alamatKtp: "Jl. Slamet Riyadi No. 50, Solo",
    alamatDomisili: "Jl. MT Haryono No. 10, Jakarta Timur",
    noTelp: "0822-3456-7890",
    tanggalBergabung: "2021-05-10",
    jabatan: "Account Manager",
    statusPernikahan: "Menikah",
    namaPasangan: "Dian Safitri",
    jumlahAnak: 2,
    fotoKtp: "/uploads/ktp-emp011.jpg",
    fotoDiri: "/uploads/foto-emp011.jpg",
    noBpjsKesehatan: "0001234567900",
    noBpjsKetenagakerjaan: "19103221991011",
    fotoSim: "/uploads/sim-emp011.jpg",
    noRekening: "1122334455",
    bank: "BCA",
    namaRekening: "Fajar Nugroho",
    kartuKeluarga: "/uploads/kk-emp011.jpg",
    tanggalMulaiPkwt: null,
    tanggalBerakhirPkwt: null,
  },
  {
    id: "ID57212",
    nama: "Lina Marlina",
    jenisKelamin: "Perempuan",
    agama: "Islam",
    status: "Tidak Aktif",
    noKtp: "3201121234560012",
    tempatLahir: "Cirebon",
    tanggalLahir: "1993-10-05",
    alamatKtp: "Jl. Siliwangi No. 12, Cirebon",
    alamatDomisili: "Jl. Siliwangi No. 12, Cirebon",
    noTelp: "0823-4567-8901",
    tanggalBergabung: "2020-02-28",
    jabatan: "Recruitment Lead",
    statusPernikahan: "Cerai",
    namaPasangan: null,
    jumlahAnak: 1,
    fotoKtp: "/uploads/ktp-emp012.jpg",
    fotoDiri: "/uploads/foto-emp012.jpg",
    noBpjsKesehatan: "0001234567901",
    noBpjsKetenagakerjaan: "19310051993012",
    fotoSim: null,
    noRekening: "2233445566",
    bank: "BRI",
    namaRekening: "Lina Marlina",
    kartuKeluarga: "/uploads/kk-emp012.jpg",
    tanggalMulaiPkwt: null,
    tanggalBerakhirPkwt: null,
  },
];

// Attendance Records
export interface AttendanceRecord {
  id: string;
  employeeName: string;
  department: string;
  date: string;
  checkIn: string;
  checkOut: string;
  status: string;
  workHours: string;
}

export const attendanceRecords: AttendanceRecord[] = [
  {
    id: "ATT-001",
    employeeName: "Budi Santoso",
    department: "Engineering",
    date: "2024-03-18",
    checkIn: "08:02",
    checkOut: "17:15",
    status: "Hadir",
    workHours: "9j 13m",
  },
  {
    id: "ATT-002",
    employeeName: "Siti Nurhaliza",
    department: "Marketing",
    date: "2024-03-18",
    checkIn: "07:55",
    checkOut: "17:30",
    status: "Hadir",
    workHours: "9j 35m",
  },
  {
    id: "ATT-003",
    employeeName: "Ahmad Fauzi",
    department: "Sales",
    date: "2024-03-18",
    checkIn: "08:30",
    checkOut: "17:00",
    status: "Terlambat",
    workHours: "8j 30m",
  },
  {
    id: "ATT-004",
    employeeName: "Dewi Lestari",
    department: "HR",
    date: "2024-03-18",
    checkIn: "08:00",
    checkOut: "17:05",
    status: "Hadir",
    workHours: "9j 5m",
  },
  {
    id: "ATT-005",
    employeeName: "Rizky Pratama",
    department: "Engineering",
    date: "2024-03-18",
    checkIn: "07:45",
    checkOut: "18:00",
    status: "Hadir",
    workHours: "10j 15m",
  },
  {
    id: "ATT-006",
    employeeName: "Maya Anggraini",
    department: "Finance",
    date: "2024-03-18",
    checkIn: "-",
    checkOut: "-",
    status: "Izin",
    workHours: "-",
  },
  {
    id: "ATT-007",
    employeeName: "Hendra Wijaya",
    department: "Operations",
    date: "2024-03-18",
    checkIn: "08:10",
    checkOut: "17:20",
    status: "Hadir",
    workHours: "9j 10m",
  },
  {
    id: "ATT-008",
    employeeName: "Putri Rahayu",
    department: "Design",
    date: "2024-03-18",
    checkIn: "-",
    checkOut: "-",
    status: "Sakit",
    workHours: "-",
  },
];

// Payroll Data
export interface PayrollRecord {
  id: string;
  employeeName: string;
  department: string;
  position: string;
  baseSalary: number;
  allowance: number;
  deduction: number;
  netSalary: number;
  status: string;
  period: string;
}

export const payrollRecords: PayrollRecord[] = [
  {
    id: "PAY-001",
    employeeName: "Budi Santoso",
    department: "Engineering",
    position: "Senior Software Engineer",
    baseSalary: 25000000,
    allowance: 5000000,
    deduction: 2500000,
    netSalary: 27500000,
    status: "Paid",
    period: "Maret 2024",
  },
  {
    id: "PAY-002",
    employeeName: "Siti Nurhaliza",
    department: "Marketing",
    position: "Marketing Manager",
    baseSalary: 22000000,
    allowance: 4500000,
    deduction: 2200000,
    netSalary: 24300000,
    status: "Paid",
    period: "Maret 2024",
  },
  {
    id: "PAY-003",
    employeeName: "Ahmad Fauzi",
    department: "Sales",
    position: "Sales Executive",
    baseSalary: 18000000,
    allowance: 3500000,
    deduction: 1800000,
    netSalary: 19700000,
    status: "Pending",
    period: "Maret 2024",
  },
  {
    id: "PAY-004",
    employeeName: "Dewi Lestari",
    department: "HR",
    position: "HR Specialist",
    baseSalary: 16000000,
    allowance: 3000000,
    deduction: 1600000,
    netSalary: 17400000,
    status: "Paid",
    period: "Maret 2024",
  },
  {
    id: "PAY-005",
    employeeName: "Rizky Pratama",
    department: "Engineering",
    position: "Frontend Developer",
    baseSalary: 20000000,
    allowance: 4000000,
    deduction: 2000000,
    netSalary: 22000000,
    status: "Pending",
    period: "Maret 2024",
  },
  {
    id: "PAY-006",
    employeeName: "Hendra Wijaya",
    department: "Operations",
    position: "Operations Manager",
    baseSalary: 28000000,
    allowance: 6000000,
    deduction: 2800000,
    netSalary: 31200000,
    status: "Paid",
    period: "Maret 2024",
  },
];

// Leave Requests
export interface LeaveRequest {
  id: string;
  employeeName: string;
  department: string;
  type: string;
  startDate: string;
  endDate: string;
  days: number;
  status: string;
  reason: string;
}

export const leaveRequests: LeaveRequest[] = [
  {
    id: "LV-001",
    employeeName: "Ahmad Fauzi",
    department: "Sales",
    type: "Cuti Tahunan",
    startDate: "2024-03-20",
    endDate: "2024-03-22",
    days: 3,
    status: "Pending",
    reason: "Acara keluarga",
  },
  {
    id: "LV-002",
    employeeName: "Putri Rahayu",
    department: "Design",
    type: "Cuti Sakit",
    startDate: "2024-03-18",
    endDate: "2024-03-19",
    days: 2,
    status: "Approved",
    reason: "Pemeriksaan kesehatan",
  },
  {
    id: "LV-003",
    employeeName: "Budi Santoso",
    department: "Engineering",
    type: "Cuti Tahunan",
    startDate: "2024-04-01",
    endDate: "2024-04-05",
    days: 5,
    status: "Pending",
    reason: "Liburan keluarga",
  },
  {
    id: "LV-004",
    employeeName: "Siti Nurhaliza",
    department: "Marketing",
    type: "Izin",
    startDate: "2024-03-25",
    endDate: "2024-03-25",
    days: 1,
    status: "Approved",
    reason: "Urusan pribadi",
  },
  {
    id: "LV-005",
    employeeName: "Hendra Wijaya",
    department: "Operations",
    type: "Cuti Tahunan",
    startDate: "2024-03-28",
    endDate: "2024-03-29",
    days: 2,
    status: "Rejected",
    reason: "Jadwal proyek padat",
  },
  {
    id: "LV-006",
    employeeName: "Rizky Pratama",
    department: "Engineering",
    type: "Izin",
    startDate: "2024-04-08",
    endDate: "2024-04-08",
    days: 1,
    status: "Pending",
    reason: "Keperluan keluarga",
  },
  {
    id: "LV-007",
    employeeName: "Maya Anggraini",
    department: "Finance",
    type: "Cuti Sakit",
    startDate: "2024-03-15",
    endDate: "2024-03-16",
    days: 2,
    status: "Approved",
    reason: "Sakit demam",
  },
  {
    id: "LV-008",
    employeeName: "Fajar Nugroho",
    department: "Sales",
    type: "Cuti Tahunan",
    startDate: "2024-04-15",
    endDate: "2024-04-19",
    days: 5,
    status: "Pending",
    reason: "Pernikahan saudara",
  },
];

// Recruitment / Candidates
export interface Candidate {
  id: string;
  name: string;
  email: string;
  phone: string;
  position: string;
  department: string;
  appliedDate: string;
  status: string;
  stage: string;
  experience: string;
  education: string;
  source: string;
}

export const candidates: Candidate[] = [
  {
    id: "CND-001",
    name: "Dimas Aditya",
    email: "dimas.aditya@gmail.com",
    phone: "+62 856-1234-5678",
    position: "Full Stack Developer",
    department: "Engineering",
    appliedDate: "2024-03-10",
    status: "Active",
    stage: "Interview HR",
    experience: "4 tahun",
    education: "S1 Teknik Informatika",
    source: "LinkedIn",
  },
  {
    id: "CND-002",
    name: "Anisa Rahma",
    email: "anisa.rahma@gmail.com",
    phone: "+62 857-2345-6789",
    position: "Digital Marketing Specialist",
    department: "Marketing",
    appliedDate: "2024-03-12",
    status: "Active",
    stage: "Interview User",
    experience: "3 tahun",
    education: "S1 Ilmu Komunikasi",
    source: "JobStreet",
  },
  {
    id: "CND-003",
    name: "Rendi Kurniawan",
    email: "rendi.k@gmail.com",
    phone: "+62 858-3456-7890",
    position: "Backend Developer",
    department: "Engineering",
    appliedDate: "2024-03-08",
    status: "Active",
    stage: "Technical Test",
    experience: "2 tahun",
    education: "S1 Sistem Informasi",
    source: "Referral",
  },
  {
    id: "CND-004",
    name: "Fitri Handayani",
    email: "fitri.h@gmail.com",
    phone: "+62 859-4567-8901",
    position: "UI/UX Designer",
    department: "Design",
    appliedDate: "2024-03-15",
    status: "Active",
    stage: "Review Portfolio",
    experience: "5 tahun",
    education: "S1 Desain Komunikasi Visual",
    source: "Website Karir",
  },
  {
    id: "CND-005",
    name: "Galih Pratama",
    email: "galih.p@gmail.com",
    phone: "+62 851-5678-9012",
    position: "Sales Executive",
    department: "Sales",
    appliedDate: "2024-03-05",
    status: "Offered",
    stage: "Offering",
    experience: "3 tahun",
    education: "S1 Manajemen",
    source: "LinkedIn",
  },
  {
    id: "CND-006",
    name: "Nadia Putri",
    email: "nadia.putri@gmail.com",
    phone: "+62 852-6789-0123",
    position: "HR Generalist",
    department: "HR",
    appliedDate: "2024-03-18",
    status: "Active",
    stage: "Screening CV",
    experience: "2 tahun",
    education: "S1 Psikologi",
    source: "Glints",
  },
  {
    id: "CND-007",
    name: "Bayu Setiawan",
    email: "bayu.s@gmail.com",
    phone: "+62 853-7890-1234",
    position: "DevOps Engineer",
    department: "Engineering",
    appliedDate: "2024-02-28",
    status: "Rejected",
    stage: "Interview HR",
    experience: "3 tahun",
    education: "S1 Teknik Informatika",
    source: "LinkedIn",
  },
  {
    id: "CND-008",
    name: "Citra Dewi",
    email: "citra.dewi@gmail.com",
    phone: "+62 854-8901-2345",
    position: "Financial Analyst",
    department: "Finance",
    appliedDate: "2024-03-20",
    status: "Active",
    stage: "Interview HR",
    experience: "4 tahun",
    education: "S1 Akuntansi",
    source: "JobStreet",
  },
  {
    id: "CND-009",
    name: "Eko Prasetyo",
    email: "eko.p@gmail.com",
    phone: "+62 855-9012-3456",
    position: "Project Manager",
    department: "Operations",
    appliedDate: "2024-03-01",
    status: "Hired",
    stage: "Onboarding",
    experience: "7 tahun",
    education: "S2 Manajemen Proyek",
    source: "Referral",
  },
  {
    id: "CND-010",
    name: "Laras Wulandari",
    email: "laras.w@gmail.com",
    phone: "+62 856-0123-4567",
    position: "Content Writer",
    department: "Marketing",
    appliedDate: "2024-03-22",
    status: "Active",
    stage: "Screening CV",
    experience: "1 tahun",
    education: "S1 Sastra Inggris",
    source: "Website Karir",
  },
];
