name = "hrweb"
main = ".open-next/worker.js"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "hrweb"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://snovvucsmewwbrnggvek.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNub3Z2dWNzbWV3d2JybmdndmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3NzU4MDYsImV4cCI6MjA5MjM1MTgwNn0.M6x1vcQKN_cJGM0B__2XE_ggcC8kro9Ch0r5qdyvW3k"

[observability]
enabled = true
