name = "hrweb"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "hrweb"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://snovvucsmewwbrnggvek.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_m299cjH9UFkF0J429f8Xew_jOk2pahO"

[observability]
enabled = true
