"use client";

import { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useState } from "react";
import {
  Plus, Search, X, Check, Trash2, Pencil, Eye, AlertTriangle,
  CalendarOff, ArrowRightLeft, UserCheck, User, Calendar,
} from "lucide-react";
import Button from "@/components/ui/Button";
import Select from "@/components/ui/Select";
import DatePicker from "@/components/ui/DatePicker";
import Portal from "@/components/ui/Portal";
import Pagination from "@/components/ui/Pagination";
import { cn } from "@/lib/utils";
import { supabase } from "@/lib/supabase";
import { logAudit } from "@/lib/audit";
import {
  AUTO_NOTES,
  AUTO_NOTE_PREFIXES,
  isAutoGeneratedNote,
  DAY_SHORT,
  HOLIDAY_COLORS,
  HOLIDAY_LIST_PAGE_SIZE,
} from "../lib/attendance-constants";
import {
  localDateStr,
  addDays,
  getCalPeriod,
  getDateRange,
  getAffectedEmployeeIds,
} from "../lib/attendance-helpers";
import type {
  EmployeeLite,
  OffDayEntry,
  OverrideEntry,
  PublicHoliday,
} from "../lib/attendance-types";
import type { ToastType } from "../lib/hooks/use-toast";
import type { HolidayDetailModalHandle } from "./holiday-detail-modal";

export type OffDayModalHandle = {
  open: () => void;
};

type OffDayModalProps = {
  employees: EmployeeLite[];
  offDays: OffDayEntry[];
  overrides: OverrideEntry[];
  publicHolidays: PublicHoliday[];
  onShowToast: (type: ToastType, title: string, message?: string) => void;
  onSaved: () => Promise<void> | void;
  detailRef: React.RefObject<HolidayDetailModalHandle | null>;
};

type Tab = "mingguan" | "custom" | "libur";

type HolidayFormState = {
  nama: string;
  tanggal: string;
  tanggal_selesai: string;
  kategori: PublicHoliday["kategori"];
  catatan: string;
  berlaku_untuk: "semua" | "divisi" | "pegawai";
  divisi_ids: number[];
  pegawai_ids: string[];
};

const EMPTY_HOLIDAY: HolidayFormState = {
  nama: "", tanggal: "", tanggal_selesai: "", kategori: "Nasional",
  catatan: "", berlaku_untuk: "semua", divisi_ids: [], pegawai_ids: [],
};

export const OffDayModal = forwardRef<OffDayModalHandle, OffDayModalProps>(function OffDayModal(
  { employees, offDays, overrides, publicHolidays, onShowToast, onSaved, detailRef },
  ref,
) {
  const [open, setOpen] = useState(false);
  const [tab, setTab] = useState<Tab>("mingguan");

  const calPeriodKey = useMemo(() => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  }, []);

  const [search, setSearch] = useState("");
  const [localMap, setLocalMap] = useState<Map<string, Set<number>>>(new Map());
  const [saving, setSaving] = useState(false);
  const [progress, setProgress] = useState<{ step: number; total: number; label: string } | null>(null);

  const [holidayForm, setHolidayForm] = useState<HolidayFormState>(EMPTY_HOLIDAY);
  const [holidayEmpSearch, setHolidayEmpSearch] = useState("");
  const [holidayListSearch, setHolidayListSearch] = useState("");
  const [holidayKategoriFilter, setHolidayKategoriFilter] = useState<"Semua" | PublicHoliday["kategori"]>("Semua");
  const [holidayListPage, setHolidayListPage] = useState(1);
  const [editingHolidayId, setEditingHolidayId] = useState<number | null>(null);
  const [holidaySaving, setHolidaySaving] = useState(false);
  const [holidayError, setHolidayError] = useState("");

  const [overrideEmpId, setOverrideEmpId] = useState("");
  const [overrideTanggal, setOverrideTanggal] = useState("");
  const [overrideType, setOverrideType] = useState<"libur" | "masuk">("libur");
  const [overrideCatatan, setOverrideCatatan] = useState("");
  const [overrideSaving, setOverrideSaving] = useState(false);

  useImperativeHandle(ref, () => ({
    open: () => {
      const map = new Map<string, Set<number>>();
      employees.forEach((e) => map.set(e.id, new Set()));
      offDays.forEach((od) => {
        if (map.has(od.employee_id)) map.get(od.employee_id)!.add(od.day_of_week);
      });
      setLocalMap(map);
      setSearch("");
      setTab("mingguan");
      setOpen(true);
    },
  }), [employees, offDays]);

  useEffect(() => {
    if (open) document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = ""; };
  }, [open]);

  const close = useCallback(() => {
    if (saving || holidaySaving || overrideSaving) return;
    setOpen(false);
  }, [saving, holidaySaving, overrideSaving]);

  const resetHolidayForm = useCallback(() => {
    setHolidayForm(EMPTY_HOLIDAY);
    setEditingHolidayId(null);
    setHolidayError("");
    setHolidayEmpSearch("");
  }, []);

  const toggleOffDay = useCallback((empId: string, day: number) => {
    setLocalMap((prev) => {
      const next = new Map(prev);
      const days = new Set(next.get(empId) || []);
      if (days.has(day)) days.delete(day); else days.add(day);
      next.set(empId, days);
      return next;
    });
  }, []);

  const syncWeeklyOffDays = useCallback(async (
    diff: { added: { empId: string; dow: number }[]; removed: { empId: string; dow: number }[] }
  ): Promise<{ inserted: number; updated: number; deleted: number }> => {
    let inserted = 0, updated = 0, deleted = 0;
    const today = localDateStr();
    const periodEnd = getCalPeriod(calPeriodKey).end;

    type Cell = { empId: string; tanggal: string; type: "add" | "remove" };
    const cells: Cell[] = [];
    const addAll = (emp: string, dow: number, type: "add" | "remove") => {
      for (let cur = today; cur <= periodEnd; cur = addDays(cur, 1)) {
        const [y, m, d] = cur.split("-").map(Number);
        const cellDow = new Date(Date.UTC(y, m - 1, d)).getUTCDay();
        if (cellDow === dow) cells.push({ empId: emp, tanggal: cur, type });
      }
    };
    diff.added.forEach((d) => addAll(d.empId, d.dow, "add"));
    diff.removed.forEach((d) => addAll(d.empId, d.dow, "remove"));

    if (cells.length === 0) return { inserted, updated, deleted };

    const empIds = [...new Set(cells.map((c) => c.empId))];
    const dates = [...new Set(cells.map((c) => c.tanggal))];
    const { data: existing } = await supabase
      .from("attendance_records")
      .select("id, employee_id, tanggal, status, catatan, is_manual")
      .in("employee_id", empIds)
      .in("tanggal", dates);
    const existingMap = new Map<string, { id: number; status: string; catatan: string | null; is_manual: boolean }>();
    (existing || []).forEach((r) => existingMap.set(`${r.employee_id}|${r.tanggal}`, r));

    const { data: ovs } = await supabase
      .from("employee_leave_overrides")
      .select("employee_id, tanggal, type")
      .in("employee_id", empIds)
      .in("tanggal", dates);
    const ovMap = new Map<string, string>();
    (ovs || []).forEach((o) => ovMap.set(`${o.employee_id}|${o.tanggal}`, o.type));

    const isPublicHolidayDate = (empId: string, tanggal: string): boolean => {
      return publicHolidays.some((h) => {
        if (tanggal < h.tanggal) return false;
        const endDate = h.tanggal_selesai || h.tanggal;
        if (tanggal > endDate) return false;
        if (h.berlaku_untuk === "semua") return true;
        if (h.berlaku_untuk === "pegawai" && h.pegawai_ids?.includes(empId)) return true;
        return false;
      });
    };

    const inserts: { employee_id: string; division_id: null; tanggal: string; jam_masuk: string; schedule_jam_masuk: string; toleransi_menit: number; status: string; durasi_telat: number; denda: number; catatan: string; is_manual: boolean }[] = [];
    const updateAlphaToLiburIds: number[] = [];
    const deleteIds: number[] = [];

    for (const cell of cells) {
      const key = `${cell.empId}|${cell.tanggal}`;
      const ex = existingMap.get(key);
      const ov = ovMap.get(key);

      if (cell.type === "add") {
        if (ov === "masuk") continue;
        if (!ex) {
          inserts.push({
            employee_id: cell.empId, division_id: null, tanggal: cell.tanggal,
            jam_masuk: "00:00", schedule_jam_masuk: "00:00", toleransi_menit: 0,
            status: "Libur", durasi_telat: 0, denda: 0,
            catatan: AUTO_NOTES.HARI_LIBUR, is_manual: false,
          });
        } else {
          if (ex.is_manual) continue;
          if (["Hadir", "Terlambat", "Izin", "Sakit", "Cuti"].includes(ex.status)) continue;
          if (ex.status === "Alpha" && (ex.catatan || "").startsWith(AUTO_NOTE_PREFIXES.ALPHA)) {
            updateAlphaToLiburIds.push(ex.id);
          }
        }
      } else {
        if (ov === "libur") continue;
        if (isPublicHolidayDate(cell.empId, cell.tanggal)) continue;
        if (!ex) continue;
        if (ex.is_manual) continue;
        if (ex.status === "Libur" && ex.catatan === AUTO_NOTES.HARI_LIBUR) {
          deleteIds.push(ex.id);
        }
      }
    }

    if (inserts.length > 0) {
      const { data: ins } = await supabase
        .from("attendance_records")
        .upsert(inserts, { onConflict: "employee_id,tanggal", ignoreDuplicates: true })
        .select("id");
      inserted = ins?.length || 0;
    }
    if (updateAlphaToLiburIds.length > 0) {
      await supabase
        .from("attendance_records")
        .update({ status: "Libur", denda: 0, durasi_telat: 0, catatan: AUTO_NOTES.HARI_LIBUR, jam_masuk: "00:00", schedule_jam_masuk: "00:00", toleransi_menit: 0 })
        .in("id", updateAlphaToLiburIds);
      updated = updateAlphaToLiburIds.length;
    }
    if (deleteIds.length > 0) {
      await supabase.from("attendance_records").delete().in("id", deleteIds);
      deleted = deleteIds.length;
    }

    return { inserted, updated, deleted };
  }, [calPeriodKey, publicHolidays]);

  const handleSaveOffDays = useCallback(async () => {
    setSaving(true);

    const oldMap = new Map<string, Set<number>>();
    offDays.forEach((od) => {
      if (!oldMap.has(od.employee_id)) oldMap.set(od.employee_id, new Set());
      oldMap.get(od.employee_id)!.add(od.day_of_week);
    });

    const added: { empId: string; dow: number }[] = [];
    const removed: { empId: string; dow: number }[] = [];
    for (const emp of employees) {
      const oldSet = oldMap.get(emp.id) || new Set<number>();
      const newSet = localMap.get(emp.id) || new Set<number>();
      for (const d of newSet) if (!oldSet.has(d)) added.push({ empId: emp.id, dow: d });
      for (const d of oldSet) if (!newSet.has(d)) removed.push({ empId: emp.id, dow: d });
    }

    const totalDays = Array.from(localMap.values()).reduce((s, days) => s + days.size, 0);

    try {
      setProgress({ step: 1, total: 3, label: `Memperbarui ${added.length + removed.length} perubahan jadwal...` });

      for (const r of removed) {
        await supabase.from("employee_off_days").delete()
          .eq("employee_id", r.empId).eq("day_of_week", r.dow);
      }
      if (added.length > 0) {
        const insertPayload = added.map((a) => ({ employee_id: a.empId, day_of_week: a.dow }));
        const { error: insError } = await supabase.from("employee_off_days").insert(insertPayload);
        if (insError) throw insError;
      }

      setProgress({ step: 2, total: 3, label: "Menyinkronkan absensi..." });
      const syncResult = await syncWeeklyOffDays({ added, removed });

      setProgress({ step: 3, total: 3, label: "Memperbarui data..." });
      await onSaved();

      if (added.length > 0 || removed.length > 0) {
        await logAudit({
          supabase,
          action: "update",
          entityType: "attendance_records",
          entityLabel: `Pergantian jadwal libur mingguan (${added.length} ditambah, ${removed.length} dihapus)`,
          metadata: {
            cutoff_date: localDateStr(),
            days_added: added.length,
            days_removed: removed.length,
            attendance_inserted: syncResult.inserted,
            attendance_updated: syncResult.updated,
            attendance_deleted: syncResult.deleted,
          },
        });
      }

      setOpen(false);
      const summary = (added.length === 0 && removed.length === 0)
        ? `${totalDays} hari libur, tidak ada perubahan.`
        : `${syncResult.inserted} baru, ${syncResult.updated} diubah, ${syncResult.deleted} dihapus (mulai hari ini).`;
      onShowToast("success", "Jadwal Libur Disimpan", summary);
    } catch (err) {
      onShowToast("error", "Gagal Menyimpan", err instanceof Error ? err.message : "Terjadi kesalahan.");
      await onSaved();
    } finally {
      setSaving(false);
      setProgress(null);
    }
  }, [employees, localMap, offDays, onSaved, onShowToast, syncWeeklyOffDays]);

  const handleAddOverride = useCallback(async () => {
    if (!overrideEmpId || !overrideTanggal) return;
    setOverrideSaving(true);
    const { error } = await supabase.from("employee_leave_overrides").upsert({
      employee_id: overrideEmpId,
      tanggal: overrideTanggal,
      type: overrideType,
      catatan: overrideCatatan || null,
    }, { onConflict: "employee_id,tanggal" });
    if (error) {
      onShowToast("error", "Gagal", error.message);
    } else {
      onShowToast("success", overrideType === "libur" ? "Libur Ditambahkan" : "Masuk Ditambahkan",
        `${employees.find((e) => e.id === overrideEmpId)?.nama || ""} — ${overrideTanggal}`);
      setOverrideEmpId("");
      setOverrideTanggal("");
      setOverrideCatatan("");
      await onSaved();
    }
    setOverrideSaving(false);
  }, [employees, onSaved, onShowToast, overrideCatatan, overrideEmpId, overrideTanggal, overrideType]);

  const handleDeleteOverride = useCallback(async (id: number) => {
    await supabase.from("employee_leave_overrides").delete().eq("id", id);
    await onSaved();
    onShowToast("success", "Override Dihapus");
  }, [onSaved, onShowToast]);

  const syncHolidayAttendance = useCallback(async (
    newHoliday: { nama: string; tanggal: string; tanggal_selesai: string | null; berlaku_untuk: string; pegawai_ids: string[] | null },
    oldHoliday: PublicHoliday | null,
  ): Promise<{ inserted: number; updated: number; deleted: number }> => {
    let inserted = 0, updated = 0, deleted = 0;

    const newDates = getDateRange(newHoliday.tanggal, newHoliday.tanggal_selesai);
    const newEmpIds = getAffectedEmployeeIds(newHoliday, employees);
    const newSet = new Set<string>();
    newDates.forEach((d) => newEmpIds.forEach((eid) => newSet.add(`${eid}|${d}`)));

    const oldDates = oldHoliday ? getDateRange(oldHoliday.tanggal, oldHoliday.tanggal_selesai) : [];
    const oldEmpIds = oldHoliday ? getAffectedEmployeeIds(oldHoliday, employees) : [];
    const oldSet = new Set<string>();
    oldDates.forEach((d) => oldEmpIds.forEach((eid) => oldSet.add(`${eid}|${d}`)));

    const toRevert: { empId: string; tanggal: string }[] = [];
    oldSet.forEach((key) => {
      if (!newSet.has(key)) {
        const [empId, tanggal] = key.split("|");
        toRevert.push({ empId, tanggal });
      }
    });

    if (toRevert.length > 0 && oldHoliday) {
      const revertEmpIds = [...new Set(toRevert.map((r) => r.empId))];
      const revertDates = [...new Set(toRevert.map((r) => r.tanggal))];
      const { data: toDelete } = await supabase
        .from("attendance_records")
        .select("id, employee_id, tanggal, catatan")
        .in("employee_id", revertEmpIds)
        .in("tanggal", revertDates)
        .eq("status", "Libur");
      const idsToDelete = (toDelete || [])
        .filter((r) => {
          if (!toRevert.some((rv) => rv.empId === r.employee_id && rv.tanggal === r.tanggal)) return false;
          return r.catatan === AUTO_NOTES.LIBUR_NASIONAL(oldHoliday.nama) || r.catatan === AUTO_NOTES.HARI_LIBUR;
        })
        .map((r) => r.id);
      if (idsToDelete.length > 0) {
        await supabase.from("attendance_records").delete().in("id", idsToDelete);
        deleted += idsToDelete.length;
      }
    }

    if (newSet.size > 0) {
      const { data: existing } = await supabase
        .from("attendance_records")
        .select("id, employee_id, tanggal, status, catatan, is_manual")
        .in("employee_id", newEmpIds)
        .in("tanggal", newDates);
      const existingMap = new Map<string, { id: number; status: string; catatan: string | null; is_manual: boolean }>();
      (existing || []).forEach((r) => existingMap.set(`${r.employee_id}|${r.tanggal}`, r));

      const inserts: { employee_id: string; division_id: null; tanggal: string; jam_masuk: string; schedule_jam_masuk: string; toleransi_menit: number; status: string; durasi_telat: number; denda: number; catatan: string; is_manual: boolean }[] = [];
      const updateIds: { id: number; catatan: string }[] = [];
      const newCatatan = `Libur nasional: ${newHoliday.nama}`;

      for (const key of newSet) {
        const [empId, tanggal] = key.split("|");
        const emp = employees.find((e) => e.id === empId);
        if (!emp) continue;
        if (emp.tanggal_bergabung && tanggal < emp.tanggal_bergabung) continue;
        if (emp.tanggal_keluar && tanggal > emp.tanggal_keluar) continue;

        const ex = existingMap.get(key);
        if (!ex) {
          inserts.push({
            employee_id: empId, division_id: null, tanggal,
            jam_masuk: "00:00", schedule_jam_masuk: "00:00", toleransi_menit: 0,
            status: "Libur", durasi_telat: 0, denda: 0,
            catatan: newCatatan, is_manual: false,
          });
        } else {
          if (ex.is_manual) continue;
          if (["Hadir", "Terlambat", "Izin", "Sakit", "Cuti"].includes(ex.status)) continue;
          if (ex.status === "Alpha" && isAutoGeneratedNote(ex.catatan)) {
            updateIds.push({ id: ex.id, catatan: newCatatan });
          } else if (ex.status === "Libur" && isAutoGeneratedNote(ex.catatan) && ex.catatan !== newCatatan) {
            updateIds.push({ id: ex.id, catatan: newCatatan });
          }
        }
      }

      if (inserts.length > 0) {
        const { data: ins } = await supabase
          .from("attendance_records")
          .upsert(inserts, { onConflict: "employee_id,tanggal", ignoreDuplicates: true })
          .select("id");
        inserted += ins?.length || 0;
      }
      if (updateIds.length > 0) {
        for (const u of updateIds) {
          await supabase
            .from("attendance_records")
            .update({ status: "Libur", denda: 0, durasi_telat: 0, catatan: u.catatan, jam_masuk: "00:00", schedule_jam_masuk: "00:00", toleransi_menit: 0 })
            .eq("id", u.id);
        }
        updated += updateIds.length;
      }
    }

    return { inserted, updated, deleted };
  }, [employees]);

  const revertHolidayAttendance = useCallback(async (h: PublicHoliday): Promise<{ deleted: number }> => {
    const dates = getDateRange(h.tanggal, h.tanggal_selesai);
    const empIds = getAffectedEmployeeIds(h, employees);
    if (dates.length === 0 || empIds.length === 0) return { deleted: 0 };

    const { data } = await supabase
      .from("attendance_records")
      .select("id, catatan")
      .in("employee_id", empIds)
      .in("tanggal", dates)
      .eq("status", "Libur");
    const idsToDelete = (data || [])
      .filter((r) => r.catatan === `Libur nasional: ${h.nama}`)
      .map((r) => r.id);
    if (idsToDelete.length > 0) {
      await supabase.from("attendance_records").delete().in("id", idsToDelete);
    }
    return { deleted: idsToDelete.length };
  }, [employees]);

  const handleSaveHoliday = useCallback(async () => {
    setHolidayError("");
    setHolidaySaving(true);
    if (!holidayForm.nama || !holidayForm.tanggal) {
      setHolidayError("Nama dan tanggal harus diisi.");
      setHolidaySaving(false);
      return;
    }
    if (holidayForm.berlaku_untuk === "pegawai" && holidayForm.pegawai_ids.length === 0) {
      setHolidayError("Pilih minimal 1 pegawai.");
      setHolidaySaving(false);
      return;
    }
    const payload = {
      nama: holidayForm.nama, tanggal: holidayForm.tanggal,
      tanggal_selesai: holidayForm.tanggal_selesai || null,
      kategori: holidayForm.kategori, catatan: holidayForm.catatan || null,
      berlaku_untuk: holidayForm.berlaku_untuk, divisi_ids: null,
      pegawai_ids: holidayForm.berlaku_untuk === "pegawai" ? holidayForm.pegawai_ids : null,
    };

    const oldHoliday = editingHolidayId ? publicHolidays.find((h) => h.id === editingHolidayId) || null : null;
    let savedId = editingHolidayId;
    if (editingHolidayId) {
      const { error } = await supabase.from("public_holidays").update(payload).eq("id", editingHolidayId);
      if (error) { setHolidayError(error.message); setHolidaySaving(false); return; }
    } else {
      const { data, error } = await supabase.from("public_holidays").insert(payload).select("id").single();
      if (error) { setHolidayError(error.message); setHolidaySaving(false); return; }
      savedId = data?.id || null;
    }

    const result = await syncHolidayAttendance(payload, oldHoliday);

    if (savedId) {
      const rangeLabel = payload.tanggal_selesai && payload.tanggal_selesai !== payload.tanggal
        ? `${payload.tanggal} s/d ${payload.tanggal_selesai}` : payload.tanggal;
      await logAudit({
        supabase,
        action: editingHolidayId ? "update" : "create",
        entityType: "attendance_records",
        entityId: String(savedId),
        entityLabel: `Sinkronisasi libur: ${payload.nama} (${rangeLabel})`,
        metadata: { holiday_id: savedId, holiday_nama: payload.nama, inserted: result.inserted, updated: result.updated, deleted: result.deleted },
      });
    }

    const summary = `${result.inserted} baru, ${result.updated} diubah, ${result.deleted} dihapus`;
    onShowToast("success", editingHolidayId ? "Hari Libur Diperbarui" : "Hari Libur Ditambahkan", summary);

    resetHolidayForm();
    await onSaved();
    setHolidaySaving(false);
  }, [editingHolidayId, holidayForm, onSaved, onShowToast, publicHolidays, resetHolidayForm, syncHolidayAttendance]);

  const handleEditHoliday = useCallback((h: PublicHoliday) => {
    setHolidayForm({
      nama: h.nama, tanggal: h.tanggal, tanggal_selesai: h.tanggal_selesai || "",
      kategori: h.kategori, catatan: h.catatan || "",
      berlaku_untuk: h.berlaku_untuk, divisi_ids: h.divisi_ids || [],
      pegawai_ids: h.pegawai_ids || [],
    });
    setEditingHolidayId(h.id);
    setHolidayError("");
    setHolidayEmpSearch("");
  }, []);

  const handleDeleteHoliday = useCallback(async (id: number) => {
    const target = publicHolidays.find((h) => h.id === id);
    const { error } = await supabase.from("public_holidays").delete().eq("id", id);
    if (error) { onShowToast("error", "Gagal", error.message); return; }

    let revertResult = { deleted: 0 };
    if (target) {
      revertResult = await revertHolidayAttendance(target);
      const rangeLabel = target.tanggal_selesai && target.tanggal_selesai !== target.tanggal
        ? `${target.tanggal} s/d ${target.tanggal_selesai}` : target.tanggal;
      await logAudit({
        supabase,
        action: "delete",
        entityType: "attendance_records",
        entityId: String(id),
        entityLabel: `Hapus sinkronisasi libur: ${target.nama} (${rangeLabel})`,
        metadata: { holiday_id: id, holiday_nama: target.nama, deleted: revertResult.deleted },
      });
    }

    onShowToast("success", "Hari Libur Dihapus", `${revertResult.deleted} record absensi dihapus`);
    await onSaved();
  }, [onSaved, onShowToast, publicHolidays, revertHolidayAttendance]);

  const openDetail = useCallback((h: PublicHoliday) => {
    detailRef.current?.open(h);
  }, [detailRef]);

  const filteredEmployees = useMemo(
    () => employees.filter((e) => e.nama.toLowerCase().includes(search.toLowerCase())),
    [employees, search],
  );

  if (!open) return null;

  return (
    <Portal>
      <div className="fixed inset-0 z-50 bg-background flex flex-col animate-fade-in">
        <div className="flex items-center justify-between px-5 py-3 border-b border-border bg-gradient-to-r from-card via-card to-violet-500/[0.03] flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-violet-500 to-violet-500/70 flex items-center justify-center shadow-sm shadow-violet-500/20">
              <CalendarOff className="w-4 h-4 text-white" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-foreground">Atur Hari Libur</h2>
              <p className="text-[10px] text-muted-foreground">Jadwal mingguan & custom per tanggal</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <div className="flex items-center bg-muted rounded-xl p-0.5">
              <button onClick={() => setTab("mingguan")}
                className={cn("flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all",
                  tab === "mingguan" ? "bg-card text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground")}>
                <CalendarOff className="w-3 h-3" />Mingguan
              </button>
              <button onClick={() => setTab("custom")}
                className={cn("flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all",
                  tab === "custom" ? "bg-card text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground")}>
                <ArrowRightLeft className="w-3 h-3" />Custom
                {overrides.length > 0 && <span className="text-[9px] font-bold bg-violet-500/10 text-violet-500 px-1.5 py-0.5 rounded">{overrides.length}</span>}
              </button>
              <button onClick={() => { setTab("libur"); resetHolidayForm(); }}
                className={cn("flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all",
                  tab === "libur" ? "bg-card text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground")}>
                <Calendar className="w-3 h-3" />Hari Libur
                {publicHolidays.length > 0 && <span className="text-[9px] font-bold bg-blue-500/10 text-blue-500 px-1.5 py-0.5 rounded">{publicHolidays.length}</span>}
              </button>
            </div>
            <button onClick={close} className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium bg-muted text-muted-foreground hover:text-foreground transition-colors">
              <X className="w-3.5 h-3.5" />Tutup
            </button>
          </div>
        </div>

        {tab === "mingguan" && (
          <div className="px-5 py-2 border-b border-border bg-card flex items-center gap-3">
            <div className="flex items-center gap-2 bg-muted rounded-xl px-3 py-2 flex-1 max-w-sm">
              <Search className="w-3.5 h-3.5 text-muted-foreground" />
              <input type="text" placeholder="Cari pegawai..." value={search} onChange={(e) => setSearch(e.target.value)}
                className="bg-transparent text-xs outline-none w-full placeholder:text-muted-foreground/50 text-foreground" />
            </div>
            <div className="flex items-center gap-3 text-[10px] text-muted-foreground">
              <span><strong className="text-foreground">{employees.length}</strong> pegawai</span>
              <span className="w-1 h-1 rounded-full bg-border" />
              <span><strong className="text-violet-500">{Array.from(localMap.values()).reduce((s, days) => s + days.size, 0)}</strong> hari libur</span>
            </div>
          </div>
        )}

        <div className="flex-1 overflow-auto">
          {tab === "mingguan" ? (
            <table className="w-full border-collapse" style={{ tableLayout: "fixed" }}>
              <colgroup>
                <col style={{ width: "180px" }} />
                {DAY_SHORT.map((_, i) => <col key={i} />)}
              </colgroup>
              <thead className="sticky top-0 z-10">
                <tr className="bg-card">
                  <th className="text-left text-[10px] font-bold text-muted-foreground uppercase tracking-wider px-3 py-3 border-b-2 border-r border-border">Pegawai</th>
                  {DAY_SHORT.map((d, i) => (
                    <th key={i} className={cn("text-center text-[10px] font-bold uppercase tracking-wider py-3 border-b-2 border-r border-border last:border-r-0",
                      i === 0 ? "text-danger/70 bg-danger/[0.03]" : i === 6 ? "text-warning/70 bg-warning/[0.03]" : "text-muted-foreground")}>{d}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {filteredEmployees.map((emp, empIdx) => {
                  const empDays = localMap.get(emp.id) || new Set<number>();
                  const offCount = empDays.size;
                  return (
                    <tr key={emp.id} className={cn("transition-colors", empIdx % 2 === 0 ? "bg-card" : "bg-muted/[0.04]", "hover:bg-violet-500/[0.03]")}>
                      <td className="px-3 py-2 border-b border-r border-border">
                        <div className="flex items-center gap-2">
                          <div className={cn("w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0",
                            offCount > 0 ? "bg-gradient-to-br from-violet-500 to-violet-600 shadow-sm shadow-violet-500/20" : "bg-primary/10")}>
                            <User className={cn("w-3.5 h-3.5", offCount > 0 ? "text-white" : "text-primary/60")} />
                          </div>
                          <div className="min-w-0 flex-1">
                            <p className="text-[11px] font-semibold text-foreground truncate">{emp.nama}</p>
                            <p className={cn("text-[9px]", offCount > 0 ? "text-violet-500" : "text-muted-foreground/30")}>
                              {offCount > 0 ? `${offCount} hari libur` : "Tidak ada libur"}
                            </p>
                          </div>
                        </div>
                      </td>
                      {DAY_SHORT.map((_, dayIdx) => {
                        const isOff = empDays.has(dayIdx);
                        const isSunday = dayIdx === 0;
                        const isSaturday = dayIdx === 6;
                        return (
                          <td key={dayIdx} className={cn(
                            "py-2 text-center border-b border-r border-border last:border-r-0",
                            isSunday ? "bg-danger/[0.02]" : isSaturday ? "bg-warning/[0.02]" : ""
                          )}>
                            <button type="button" onClick={() => toggleOffDay(emp.id, dayIdx)}
                              className={cn(
                                "w-10 h-9 rounded-lg text-[10px] font-extrabold transition-all mx-auto block",
                                isOff
                                  ? "bg-gradient-to-b from-violet-500 to-violet-600 text-white shadow-md shadow-violet-500/25 hover:shadow-lg hover:shadow-violet-500/30 scale-105"
                                  : "bg-muted/40 text-muted-foreground/15 hover:bg-violet-500/10 hover:text-violet-500 hover:scale-105"
                              )}>
                              {isOff ? "OFF" : "•"}
                            </button>
                          </td>
                        );
                      })}
                    </tr>
                  );
                })}
              </tbody>
            </table>
          ) : tab === "custom" ? (
            <div className="p-5 space-y-5">
              <div className="rounded-2xl border-2 border-dashed border-violet-500/20 bg-gradient-to-br from-violet-500/[0.03] to-transparent p-5 space-y-4">
                <div className="flex items-center gap-2">
                  <div className="w-7 h-7 rounded-lg bg-violet-500/10 flex items-center justify-center">
                    <Plus className="w-3.5 h-3.5 text-violet-500" />
                  </div>
                  <p className="text-xs font-bold text-foreground">Tambah Tukar Libur / Masuk Backup</p>
                </div>

                <div className="grid grid-cols-3 gap-3">
                  <div>
                    <label className="text-[10px] font-semibold text-muted-foreground mb-1.5 block">Pegawai</label>
                    <Select value={overrideEmpId} onChange={setOverrideEmpId}
                      options={employees.map((e) => ({ value: e.id, label: e.nama }))} placeholder="Pilih pegawai" searchable />
                  </div>
                  <div>
                    <label className="text-[10px] font-semibold text-muted-foreground mb-1.5 block">Tanggal</label>
                    <DatePicker value={overrideTanggal} onChange={setOverrideTanggal} placeholder="Pilih tanggal" />
                  </div>
                  <div>
                    <label className="text-[10px] font-semibold text-muted-foreground mb-1.5 block">Catatan</label>
                    <input type="text" placeholder="Opsional..." value={overrideCatatan}
                      onChange={(e) => setOverrideCatatan(e.target.value)}
                      className="w-full text-xs px-3 py-2.5 rounded-xl border border-border bg-muted/30 outline-none focus:border-primary text-foreground placeholder:text-muted-foreground/50" />
                  </div>
                </div>

                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <button type="button" onClick={() => setOverrideType("libur")}
                      className={cn("flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-bold transition-all border-2",
                        overrideType === "libur"
                          ? "border-violet-500 bg-violet-500/10 text-violet-500 shadow-sm shadow-violet-500/10"
                          : "border-border bg-card text-muted-foreground hover:border-violet-500/30")}>
                      <CalendarOff className="w-3.5 h-3.5" />
                      Tukar Libur
                    </button>
                    <button type="button" onClick={() => setOverrideType("masuk")}
                      className={cn("flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-bold transition-all border-2",
                        overrideType === "masuk"
                          ? "border-success bg-success/10 text-success shadow-sm shadow-success/10"
                          : "border-border bg-card text-muted-foreground hover:border-success/30")}>
                      <UserCheck className="w-3.5 h-3.5" />
                      Masuk Backup
                    </button>
                  </div>
                  <Button size="sm" icon={Plus} onClick={handleAddOverride} disabled={overrideSaving || !overrideEmpId || !overrideTanggal}>
                    {overrideSaving ? "Menyimpan..." : "Tambah"}
                  </Button>
                </div>
              </div>

              {overrides.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-16">
                  <ArrowRightLeft className="w-10 h-10 text-muted-foreground/15 mb-3" />
                  <p className="text-sm text-muted-foreground">Belum ada tukar libur atau masuk backup</p>
                  <p className="text-xs text-muted-foreground/60 mt-1">Gunakan form di atas untuk menambahkan</p>
                </div>
              ) : (
                <div className="space-y-2">
                  {overrides.map((o) => {
                    const empNama = employees.find((e) => e.id === o.employee_id)?.nama || o.employee_id;
                    const isLibur = o.type === "libur";
                    return (
                      <div key={o.id} className={cn("flex items-center gap-3 px-4 py-3 rounded-xl border transition-colors hover:bg-muted/30",
                        isLibur ? "border-violet-500/15 bg-violet-500/[0.02]" : "border-success/15 bg-success/[0.02]")}>
                        <div className={cn("w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0",
                          isLibur ? "bg-violet-500/10" : "bg-success/10")}>
                          {isLibur ? <CalendarOff className="w-3.5 h-3.5 text-violet-500" /> : <UserCheck className="w-3.5 h-3.5 text-success" />}
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2">
                            <p className="text-xs font-semibold text-foreground">{empNama}</p>
                            <span className={cn("text-[9px] font-bold px-1.5 py-0.5 rounded-md",
                              isLibur ? "bg-violet-500/10 text-violet-500" : "bg-success/10 text-success")}>
                              {isLibur ? "Tukar Libur" : "Masuk Backup"}
                            </span>
                          </div>
                          <div className="flex items-center gap-2 mt-0.5">
                            <p className="text-[10px] text-muted-foreground">
                              {new Date(o.tanggal + "T00:00:00").toLocaleDateString("id-ID", { weekday: "long", day: "numeric", month: "long", year: "numeric" })}
                            </p>
                            {o.catatan && (
                              <>
                                <span className="w-1 h-1 rounded-full bg-border" />
                                <p className="text-[10px] text-muted-foreground/70">{o.catatan}</p>
                              </>
                            )}
                          </div>
                        </div>
                        <button onClick={() => handleDeleteOverride(o.id)}
                          className="p-1.5 rounded-lg hover:bg-danger-light text-muted-foreground/40 hover:text-danger transition-colors flex-shrink-0">
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          ) : (
            <div className="p-5 space-y-5">
              <div className="rounded-2xl border-2 border-dashed border-blue-500/20 bg-gradient-to-br from-blue-500/[0.03] to-transparent p-5 space-y-4">
                <div className="flex items-center gap-2">
                  <div className="w-7 h-7 rounded-lg bg-blue-500/10 flex items-center justify-center">
                    <Plus className="w-3.5 h-3.5 text-blue-500" />
                  </div>
                  <p className="text-xs font-bold text-foreground">{editingHolidayId ? "Edit Hari Libur" : "Tambah Hari Libur Nasional"}</p>
                </div>
                {holidayError && (
                  <div className="flex items-center gap-2 px-3 py-2 rounded-xl bg-danger/10 text-danger text-xs font-medium">
                    <AlertTriangle className="w-3.5 h-3.5" />{holidayError}
                  </div>
                )}
                <div>
                  <label className="text-[10px] font-semibold text-muted-foreground mb-1.5 block">Nama Hari Libur</label>
                  <input type="text" placeholder="Misal: Idul Fitri 1448 H, Natal 2026..." value={holidayForm.nama}
                    onChange={(e) => setHolidayForm({ ...holidayForm, nama: e.target.value })}
                    className="w-full text-xs px-3 py-2.5 rounded-xl border border-border bg-muted/30 outline-none focus:border-primary text-foreground placeholder:text-muted-foreground/50" />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-[10px] font-semibold text-muted-foreground mb-1.5 block">Tanggal Mulai</label>
                    <DatePicker value={holidayForm.tanggal} onChange={(val) => setHolidayForm({ ...holidayForm, tanggal: val })} placeholder="Pilih tanggal" />
                  </div>
                  <div>
                    <label className="text-[10px] font-semibold text-muted-foreground mb-1.5 block">Tanggal Selesai <span className="text-muted-foreground/50 font-normal">(opsional)</span></label>
                    <DatePicker value={holidayForm.tanggal_selesai} onChange={(val) => setHolidayForm({ ...holidayForm, tanggal_selesai: val })} placeholder="Sama dengan mulai" />
                  </div>
                </div>
                <div>
                  <label className="text-[10px] font-semibold text-muted-foreground mb-1.5 block">Kategori</label>
                  <div className="flex items-center gap-2">
                    {(["Nasional", "Cuti Bersama", "Spesial"] as const).map((k) => (
                      <button key={k} type="button" onClick={() => setHolidayForm({ ...holidayForm, kategori: k })}
                        className={cn("flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold transition-all border-2",
                          holidayForm.kategori === k ? "border-blue-500 bg-blue-500/10 text-blue-500" : "border-border bg-card text-muted-foreground hover:border-blue-500/30")}>
                        <span className="w-2 h-2 rounded-full" style={{ backgroundColor: HOLIDAY_COLORS[k] }} />{k}
                      </button>
                    ))}
                  </div>
                </div>
                <div>
                  <label className="text-[10px] font-semibold text-muted-foreground mb-1.5 block">Catatan <span className="text-muted-foreground/50 font-normal">(opsional)</span></label>
                  <input type="text" placeholder="Keterangan tambahan..." value={holidayForm.catatan}
                    onChange={(e) => setHolidayForm({ ...holidayForm, catatan: e.target.value })}
                    className="w-full text-xs px-3 py-2.5 rounded-xl border border-border bg-muted/30 outline-none focus:border-primary text-foreground placeholder:text-muted-foreground/50" />
                </div>
                <div>
                  <label className="text-[10px] font-semibold text-muted-foreground mb-1.5 block">Berlaku Untuk</label>
                  <div className="flex items-center gap-2">
                    <button type="button" onClick={() => setHolidayForm({ ...holidayForm, berlaku_untuk: "semua", pegawai_ids: [] })}
                      className={cn("flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold transition-all border-2",
                        holidayForm.berlaku_untuk === "semua" ? "border-success bg-success/10 text-success" : "border-border bg-card text-muted-foreground hover:border-success/30")}>
                      <UserCheck className="w-3.5 h-3.5" />
                      Semua Pegawai
                    </button>
                    <button type="button" onClick={() => setHolidayForm({ ...holidayForm, berlaku_untuk: "pegawai" })}
                      className={cn("flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold transition-all border-2",
                        holidayForm.berlaku_untuk === "pegawai" ? "border-orange-500 bg-orange-500/10 text-orange-500" : "border-border bg-card text-muted-foreground hover:border-orange-500/30")}>
                      <User className="w-3.5 h-3.5" />
                      Pilih Pegawai
                      {holidayForm.berlaku_untuk === "pegawai" && holidayForm.pegawai_ids.length > 0 && (
                        <span className="text-[9px] font-bold bg-orange-500/20 text-orange-600 px-1.5 py-0.5 rounded">{holidayForm.pegawai_ids.length}</span>
                      )}
                    </button>
                  </div>
                </div>

                {holidayForm.berlaku_untuk === "pegawai" && (
                  <div className="rounded-xl border-2 border-orange-500/15 bg-orange-500/[0.02] p-3 space-y-2">
                    <div className="flex items-center gap-2">
                      <div className="flex items-center gap-2 bg-card rounded-lg px-3 py-1.5 flex-1 border border-border">
                        <Search className="w-3 h-3 text-muted-foreground" />
                        <input type="text" placeholder="Cari pegawai..." value={holidayEmpSearch}
                          onChange={(e) => setHolidayEmpSearch(e.target.value)}
                          className="bg-transparent text-[11px] outline-none w-full text-foreground placeholder:text-muted-foreground/50" />
                      </div>
                      <button type="button" onClick={() => setHolidayForm({ ...holidayForm, pegawai_ids: employees.map((e) => e.id) })}
                        className="text-[10px] font-bold text-orange-500 hover:text-orange-600 px-2 py-1 rounded">Pilih Semua</button>
                      <button type="button" onClick={() => setHolidayForm({ ...holidayForm, pegawai_ids: [] })}
                        className="text-[10px] font-bold text-muted-foreground hover:text-foreground px-2 py-1 rounded">Hapus Semua</button>
                    </div>
                    <div className="max-h-44 overflow-y-auto space-y-1 pr-1">
                      {employees
                        .filter((e) => e.nama.toLowerCase().includes(holidayEmpSearch.toLowerCase()))
                        .map((e) => {
                          const checked = holidayForm.pegawai_ids.includes(e.id);
                          return (
                            <label key={e.id}
                              className={cn("flex items-center gap-2 px-2.5 py-1.5 rounded-lg cursor-pointer transition-colors",
                                checked ? "bg-orange-500/10" : "hover:bg-muted/50")}>
                              <input type="checkbox" checked={checked}
                                onChange={(ev) => {
                                  if (ev.target.checked) {
                                    setHolidayForm({ ...holidayForm, pegawai_ids: [...holidayForm.pegawai_ids, e.id] });
                                  } else {
                                    setHolidayForm({ ...holidayForm, pegawai_ids: holidayForm.pegawai_ids.filter((id) => id !== e.id) });
                                  }
                                }}
                                className="w-3.5 h-3.5 rounded accent-orange-500 cursor-pointer" />
                              <span className="text-[11px] font-medium text-foreground flex-1">{e.nama}</span>
                            </label>
                          );
                        })}
                      {employees.filter((e) => e.nama.toLowerCase().includes(holidayEmpSearch.toLowerCase())).length === 0 && (
                        <p className="text-[10px] text-muted-foreground/50 text-center py-3">Tidak ditemukan</p>
                      )}
                    </div>
                    <div className="flex items-center justify-between pt-1.5 border-t border-orange-500/10">
                      <span className="text-[10px] text-muted-foreground">
                        <strong className="text-orange-500">{holidayForm.pegawai_ids.length}</strong> dari {employees.length} pegawai dipilih
                      </span>
                    </div>
                  </div>
                )}

                <div className="flex items-center justify-end gap-2 pt-1">
                  <div className="flex items-center gap-2">
                    {editingHolidayId && <Button variant="outline" size="sm" onClick={resetHolidayForm}>Batal Edit</Button>}
                    <Button size="sm" icon={editingHolidayId ? Check : Plus} onClick={handleSaveHoliday} disabled={holidaySaving || !holidayForm.nama || !holidayForm.tanggal}>
                      {holidaySaving ? "Menyimpan..." : editingHolidayId ? "Simpan" : "Tambah"}
                    </Button>
                  </div>
                </div>
              </div>
              {publicHolidays.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-16">
                  <Calendar className="w-10 h-10 text-muted-foreground/15 mb-3" />
                  <p className="text-sm text-muted-foreground">Belum ada hari libur nasional</p>
                  <p className="text-xs text-muted-foreground/60 mt-1">Gunakan form di atas untuk menambahkan</p>
                </div>
              ) : (() => {
                const filtered = publicHolidays.filter((h) => {
                  if (holidayKategoriFilter !== "Semua" && h.kategori !== holidayKategoriFilter) return false;
                  if (holidayListSearch) {
                    const q = holidayListSearch.toLowerCase();
                    if (!h.nama.toLowerCase().includes(q) && !(h.catatan || "").toLowerCase().includes(q)) return false;
                  }
                  return true;
                });
                const total = filtered.length;
                const totalPages = Math.max(1, Math.ceil(total / HOLIDAY_LIST_PAGE_SIZE));
                const safePage = Math.min(holidayListPage, totalPages);
                const paged = filtered.slice((safePage - 1) * HOLIDAY_LIST_PAGE_SIZE, safePage * HOLIDAY_LIST_PAGE_SIZE);

                return (
                  <div className="space-y-3">
                    <div className="flex items-center gap-2 flex-wrap">
                      <div className="flex items-center gap-2 bg-muted/40 rounded-xl px-3 py-2 flex-1 min-w-[200px]">
                        <Search className="w-3.5 h-3.5 text-muted-foreground" />
                        <input type="text" placeholder="Cari nama hari libur..." value={holidayListSearch}
                          onChange={(e) => { setHolidayListSearch(e.target.value); setHolidayListPage(1); }}
                          className="bg-transparent text-xs outline-none w-full text-foreground placeholder:text-muted-foreground/50" />
                        {holidayListSearch && (
                          <button onClick={() => setHolidayListSearch("")} className="text-muted-foreground hover:text-foreground">
                            <X className="w-3 h-3" />
                          </button>
                        )}
                      </div>
                      <div className="flex items-center bg-muted/40 rounded-xl p-1">
                        {(["Semua", "Nasional", "Cuti Bersama", "Spesial"] as const).map((k) => (
                          <button key={k} onClick={() => { setHolidayKategoriFilter(k); setHolidayListPage(1); }}
                            className={cn("px-2.5 py-1.5 rounded-lg text-[10px] font-bold transition-all",
                              holidayKategoriFilter === k ? "bg-card text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground")}>
                            {k}
                          </button>
                        ))}
                      </div>
                      <span className="text-[10px] text-muted-foreground">
                        <strong className="text-foreground">{total}</strong> dari {publicHolidays.length}
                      </span>
                    </div>

                    {paged.length === 0 ? (
                      <div className="flex flex-col items-center justify-center py-10">
                        <Search className="w-8 h-8 text-muted-foreground/15 mb-2" />
                        <p className="text-xs text-muted-foreground">Tidak ditemukan hari libur sesuai filter</p>
                      </div>
                    ) : (
                      <div className="space-y-2">
                        {paged.map((h) => (
                          <div key={h.id} className="flex items-center gap-3 px-4 py-3 rounded-xl border border-blue-500/10 bg-blue-500/[0.02] transition-colors hover:bg-muted/30">
                            <div className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 bg-blue-500/10">
                              <Calendar className="w-3.5 h-3.5 text-blue-500" />
                            </div>
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center gap-2 flex-wrap">
                                <p className="text-xs font-semibold text-foreground">{h.nama}</p>
                                <span className="text-[9px] font-bold px-1.5 py-0.5 rounded-md" style={{ backgroundColor: `${HOLIDAY_COLORS[h.kategori]}15`, color: HOLIDAY_COLORS[h.kategori] }}>{h.kategori}</span>
                                {h.berlaku_untuk === "semua" ? (
                                  <span className="inline-flex items-center gap-1 text-[9px] font-bold px-1.5 py-0.5 rounded-md bg-success/10 text-success">
                                    <UserCheck className="w-2.5 h-2.5" />Semua pegawai
                                  </span>
                                ) : (
                                  <span className="inline-flex items-center gap-1 text-[9px] font-bold px-1.5 py-0.5 rounded-md bg-orange-500/10 text-orange-500">
                                    <User className="w-2.5 h-2.5" />{h.pegawai_ids?.length || 0} pegawai
                                  </span>
                                )}
                              </div>
                              <div className="flex items-center gap-2 mt-0.5">
                                <p className="text-[10px] text-muted-foreground">
                                  {new Date(h.tanggal + "T00:00:00").toLocaleDateString("id-ID", { day: "numeric", month: "long", year: "numeric" })}
                                  {h.tanggal_selesai && h.tanggal_selesai !== h.tanggal && (
                                    <>{" — "}{new Date(h.tanggal_selesai + "T00:00:00").toLocaleDateString("id-ID", { day: "numeric", month: "long", year: "numeric" })}</>
                                  )}
                                </p>
                                {h.catatan && (
                                  <>
                                    <span className="w-1 h-1 rounded-full bg-border" />
                                    <p className="text-[10px] text-muted-foreground/70">{h.catatan}</p>
                                  </>
                                )}
                              </div>
                            </div>
                            <div className="flex items-center gap-1 flex-shrink-0">
                              <button onClick={() => openDetail(h)}
                                className="p-1.5 rounded-lg hover:bg-blue-500/10 text-muted-foreground/40 hover:text-blue-500 transition-colors"
                                title="Lihat detail pegawai libur">
                                <Eye className="w-3.5 h-3.5" />
                              </button>
                              <button onClick={() => handleEditHoliday(h)}
                                className="p-1.5 rounded-lg hover:bg-muted text-muted-foreground/40 hover:text-foreground transition-colors">
                                <Pencil className="w-3.5 h-3.5" />
                              </button>
                              <button onClick={() => handleDeleteHoliday(h.id)}
                                className="p-1.5 rounded-lg hover:bg-danger-light text-muted-foreground/40 hover:text-danger transition-colors">
                                <Trash2 className="w-3.5 h-3.5" />
                              </button>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}

                    {totalPages > 1 && (
                      <Pagination currentPage={safePage} totalItems={total} pageSize={HOLIDAY_LIST_PAGE_SIZE} onPageChange={setHolidayListPage} />
                    )}
                  </div>
                );
              })()}
            </div>
          )}
        </div>

        {tab === "mingguan" && (
          <div className="px-5 py-3 border-t border-border bg-card flex-shrink-0">
            {progress ? (
              <div className="space-y-2.5 animate-fade-in">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-5 h-5 rounded-full border-2 border-violet-500 border-t-transparent animate-spin" />
                    <span className="text-xs font-semibold text-foreground">{progress.label}</span>
                  </div>
                  <span className="text-[10px] font-bold text-muted-foreground bg-muted px-2 py-0.5 rounded-md">
                    {progress.step}/{progress.total}
                  </span>
                </div>
                <div className="w-full h-2 rounded-full bg-muted overflow-hidden">
                  <div
                    className="h-full rounded-full bg-gradient-to-r from-violet-500 to-primary transition-all duration-500 ease-out"
                    style={{ width: `${(progress.step / progress.total) * 100}%` }}
                  />
                </div>
              </div>
            ) : (
              <div className="flex items-center justify-end gap-2">
                <Button variant="outline" size="sm" onClick={close} disabled={saving}>Batal</Button>
                <Button size="sm" icon={Check} onClick={handleSaveOffDays} disabled={saving}>Simpan Jadwal</Button>
              </div>
            )}
          </div>
        )}
      </div>
    </Portal>
  );
});
