CREATE TABLE public.recruitments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama varchar(200) NOT NULL,
  no_hp varchar(20) NOT NULL,
  email varchar(100),
  posisi_dilamar varchar(100) NOT NULL,
  pendidikan_terakhir varchar(50) NOT NULL,
  pengalaman_kerja text,
  alamat text,
  cv_url text,
  status varchar(30) NOT NULL DEFAULT 'Baru'::varchar,
  catatan text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT recruitments_status_check CHECK (status::text = ANY (ARRAY['Baru', 'Screening', 'Interview', 'Diterima', 'Ditolak']::text[]))
);

CREATE INDEX idx_recruitments_status ON public.recruitments USING btree (status);
CREATE TRIGGER trg_recruitments_updated_at BEFORE UPDATE ON public.recruitments FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
ALTER TABLE public.recruitments ENABLE ROW LEVEL SECURITY;
CREATE POLICY allow_all_recruitments ON public.recruitments FOR ALL TO public USING (true) WITH CHECK (true);

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('recruitment-docs', 'recruitment-docs', true, 5242880, '{"application/pdf"}')
ON CONFLICT (id) DO NOTHING;
