-- ============================================================
-- Redesign: Lokasi absen many-to-many dengan divisi
-- ============================================================

-- 1. Hapus tabel lama
DROP TABLE IF EXISTS public.division_locations;

-- 2. Tabel lokasi absen (master)
CREATE TABLE public.attendance_locations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama varchar(100) NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  radius integer NOT NULL DEFAULT 100,
  status varchar(20) NOT NULL DEFAULT 'Aktif'::varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT attendance_locations_status_check CHECK (
    status::text = ANY (ARRAY['Aktif', 'Tidak Aktif']::text[])
  ),
  CONSTRAINT attendance_locations_radius_check CHECK (radius > 0)
);

CREATE TRIGGER trg_attendance_locations_updated_at
  BEFORE UPDATE ON public.attendance_locations
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

ALTER TABLE public.attendance_locations ENABLE ROW LEVEL SECURITY;
CREATE POLICY allow_all_attendance_locations ON public.attendance_locations
  FOR ALL TO public USING (true) WITH CHECK (true);

-- 3. Tabel pivot: divisi <-> lokasi (many-to-many)
CREATE TABLE public.division_location_assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  division_id integer NOT NULL REFERENCES public.divisions(id) ON DELETE CASCADE,
  location_id integer NOT NULL REFERENCES public.attendance_locations(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT division_location_unique UNIQUE (division_id, location_id)
);

CREATE INDEX idx_dla_division ON public.division_location_assignments USING btree (division_id);
CREATE INDEX idx_dla_location ON public.division_location_assignments USING btree (location_id);

ALTER TABLE public.division_location_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY allow_all_division_location_assignments ON public.division_location_assignments
  FOR ALL TO public USING (true) WITH CHECK (true);
