-- Superseded by 20260830010000_simplify_account_password_storage.sql.
-- The encrypted password store was replaced with a simpler plaintext copy table
-- by product requirement before this migration was applied to production.
