-- ============================================================
-- Harga per titik berdasarkan divisi + role (Driver/Helper)
-- ============================================================
CREATE TABLE public.point_rates (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  division_id integer NOT NULL REFERENCES public.divisions(id) ON DELETE CASCADE,
  role varchar(20) NOT NULL,
  rate_per_point integer NOT NULL DEFAULT 0,
  status varchar(20) NOT NULL DEFAULT 'Aktif'::varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT point_rates_role_check CHECK (role::text = ANY (ARRAY['Driver', 'Helper']::text[])),
  CONSTRAINT point_rates_status_check CHECK (status::text = ANY (ARRAY['Aktif', 'Tidak Aktif']::text[])),
  CONSTRAINT point_rates_division_role_unique UNIQUE (division_id, role),
  CONSTRAINT point_rates_rate_check CHECK (rate_per_point >= 0)
);

CREATE TRIGGER trg_point_rates_updated_at
  BEFORE UPDATE ON public.point_rates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

ALTER TABLE public.point_rates ENABLE ROW LEVEL SECURITY;
CREATE POLICY allow_all_point_rates ON public.point_rates FOR ALL TO public USING (true) WITH CHECK (true);

-- ============================================================
-- Input titik harian driver/helper
-- ============================================================
CREATE TABLE public.delivery_points (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id varchar(20) NOT NULL REFERENCES public.pegawai(id) ON DELETE CASCADE,
  division_id integer NOT NULL REFERENCES public.divisions(id),
  role varchar(20) NOT NULL,
  tanggal date NOT NULL,
  jumlah_titik integer NOT NULL DEFAULT 0,
  rate_per_point integer NOT NULL DEFAULT 0,
  total integer GENERATED ALWAYS AS (jumlah_titik * rate_per_point) STORED,
  catatan text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT delivery_points_role_check CHECK (role::text = ANY (ARRAY['Driver', 'Helper']::text[])),
  CONSTRAINT delivery_points_titik_check CHECK (jumlah_titik >= 0),
  CONSTRAINT delivery_points_rate_check CHECK (rate_per_point >= 0)
);

CREATE INDEX idx_delivery_points_employee ON public.delivery_points USING btree (employee_id);
CREATE INDEX idx_delivery_points_tanggal ON public.delivery_points USING btree (tanggal);
CREATE INDEX idx_delivery_points_division ON public.delivery_points USING btree (division_id);

CREATE TRIGGER trg_delivery_points_updated_at
  BEFORE UPDATE ON public.delivery_points
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

ALTER TABLE public.delivery_points ENABLE ROW LEVEL SECURITY;
CREATE POLICY allow_all_delivery_points ON public.delivery_points FOR ALL TO public USING (true) WITH CHECK (true);
