-- ============================================================
-- Security master tables for mobile attendance & face profile
-- ============================================================

-- Device ID per employee (for future Android attendance app)
CREATE TABLE IF NOT EXISTS public.employee_devices (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id varchar(20) NOT NULL REFERENCES public.pegawai(id) ON DELETE CASCADE,
  device_id varchar(150) NOT NULL,
  platform varchar(30) DEFAULT 'Android',
  status varchar(20) NOT NULL DEFAULT 'Aktif'::varchar,
  registered_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT employee_devices_status_check CHECK (
    status::text = ANY (ARRAY['Aktif', 'Tidak Aktif']::text[])
  ),
  CONSTRAINT employee_devices_employee_unique UNIQUE (employee_id),
  CONSTRAINT employee_devices_device_unique UNIQUE (device_id)
);

CREATE INDEX IF NOT EXISTS idx_employee_devices_status ON public.employee_devices USING btree (status);

CREATE TRIGGER trg_employee_devices_updated_at
  BEFORE UPDATE ON public.employee_devices
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

ALTER TABLE public.employee_devices ENABLE ROW LEVEL SECURITY;
CREATE POLICY allow_all_employee_devices ON public.employee_devices
  FOR ALL TO public
  USING (true) WITH CHECK (true);

-- Face profile per employee (for future face attendance)
CREATE TABLE IF NOT EXISTS public.employee_face_profiles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id varchar(20) NOT NULL REFERENCES public.pegawai(id) ON DELETE CASCADE,
  face_data_ref text,
  reference_image_url text,
  quality_score numeric(5,2),
  status varchar(20) NOT NULL DEFAULT 'Aktif'::varchar,
  enrolled_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT employee_face_profiles_status_check CHECK (
    status::text = ANY (ARRAY['Aktif', 'Tidak Aktif']::text[])
  ),
  CONSTRAINT employee_face_profiles_employee_unique UNIQUE (employee_id),
  CONSTRAINT employee_face_profiles_quality_check CHECK (
    quality_score IS NULL OR (quality_score >= 0 AND quality_score <= 100)
  )
);

CREATE INDEX IF NOT EXISTS idx_employee_face_profiles_status ON public.employee_face_profiles USING btree (status);

CREATE TRIGGER trg_employee_face_profiles_updated_at
  BEFORE UPDATE ON public.employee_face_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

ALTER TABLE public.employee_face_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY allow_all_employee_face_profiles ON public.employee_face_profiles
  FOR ALL TO public
  USING (true) WITH CHECK (true);
