CREATE TABLE public.delivery_statuses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama varchar(50) NOT NULL,
  kode varchar(10) NOT NULL,
  color varchar(7) DEFAULT '#6b7280',
  status varchar(20) NOT NULL DEFAULT 'Aktif'::varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT delivery_statuses_status_check CHECK (status::text = ANY (ARRAY['Aktif', 'Tidak Aktif']::text[]))
);

CREATE TRIGGER trg_delivery_statuses_updated_at
  BEFORE UPDATE ON public.delivery_statuses
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

ALTER TABLE public.delivery_statuses ENABLE ROW LEVEL SECURITY;
CREATE POLICY allow_all_delivery_statuses ON public.delivery_statuses FOR ALL TO public USING (true) WITH CHECK (true);

INSERT INTO public.delivery_statuses (nama, kode, color) VALUES ('Aktif', 'AKT', '#10b981'), ('Standby', 'STB', '#f59e0b');

ALTER TABLE public.delivery_points ADD COLUMN IF NOT EXISTS status_id integer REFERENCES public.delivery_statuses(id);
