-- ────────────────────────────────────────────
-- TABLE: divisions
-- Master data divisi/departemen
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.divisions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama varchar(100) NOT NULL,
  deskripsi text,
  status varchar(20) NOT NULL DEFAULT 'Aktif'::varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT divisions_status_check CHECK (
    status::text = ANY (ARRAY['Aktif', 'Tidak Aktif']::text[])
  )
);

-- Trigger: auto-update updated_at
CREATE TRIGGER trg_divisions_updated_at
  BEFORE UPDATE ON public.divisions
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

-- Enable RLS
ALTER TABLE public.divisions ENABLE ROW LEVEL SECURITY;

-- Policy
CREATE POLICY allow_all_divisions ON public.divisions
  FOR ALL TO public
  USING (true) WITH CHECK (true);
