-- Seed SLA Tuku CP: 12 profil rute VAN + 63 titik + SLA berangkat VAN 1-7.
-- Sumber: "Plaan Rute Sabang + NSO BP JGC.xlsx", berlaku 2026-09-29.
-- BSD Online (VAN 12) belum punya address_id McEasy -> tanpa mapping,
-- ditandai unresolved di Pengaturan SLA hingga ID ditemukan.
-- Idempotent (aman dijalankan ulang).

-- VAN 1 (depart: 4:15)
insert into public.tms_sla_route_profiles (client_id, group_id, code, name, departure_target_time, effective_from, status, source_file) values ((select id from public.tms_clients where code = 'TUKU'), (select id from public.tms_live_track_groups where lower(name) = 'cp'), 'VAN 1', 'VAN 1 CP Tuku', '4:15', '2026-09-29', 'Aktif', 'Plaan Rute Sabang + NSO BP JGC.xlsx') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 1'), 1, 'Toko Kopi Tuku Jati asih', 'jati asih', '04:58:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 1') and st.route_order = 1), '272', 'Toko Kopi Tuku Jati asih', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 1'), 2, 'Toko Kopi Tuku Grand Wisata', 'grand wisata', '05:56:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 1') and st.route_order = 2), '154625', 'Toko Kopi Tuku Grand Wisata', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 1'), 3, 'Toko Kopi Tuku Vida Bekasi', 'vida bekasi', '06:25:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 1') and st.route_order = 3), '273', 'Toko Kopi Tuku Vida Bekasi', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 1'), 4, 'Toko Kopi Tuku Kota Wisata Cibubur', 'kota wisata cibubur', '07:03:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 1') and st.route_order = 4), '6117', 'Toko Kopi Tuku Kota Wisata Cibubur', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 1'), 5, 'Toko Kopi Tuku Bp Cibubur', 'bp cibubur', '07:22:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 1') and st.route_order = 5), '278', 'Toko Kopi Tuku Bp Cibubur', true) on conflict do nothing;
-- VAN 2 (depart: 4:21)
insert into public.tms_sla_route_profiles (client_id, group_id, code, name, departure_target_time, effective_from, status, source_file) values ((select id from public.tms_clients where code = 'TUKU'), (select id from public.tms_live_track_groups where lower(name) = 'cp'), 'VAN 2', 'VAN 2 CP Tuku', '4:21', '2026-09-29', 'Aktif', 'Plaan Rute Sabang + NSO BP JGC.xlsx') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 2'), 1, 'Toko Kopi Tuku Cempaka putih', 'cempaka putih', '05:04:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 2') and st.route_order = 1), '30533', 'Toko Kopi Tuku Cempaka putih', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 2'), 2, 'Toko kopi tuku Bp Sunter', 'bp sunter', '05:58:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 2') and st.route_order = 2), '285', 'Toko kopi tuku Bp Sunter', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 2'), 3, 'Toko Kopi Tuku Kelapa gading', 'kelapa gading', '06:23:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 2') and st.route_order = 3), '286', 'Toko Kopi Tuku Kelapa gading', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 2'), 4, 'Toko Kopi Tuku BP JGC', 'bp jgc', '07:05:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 2') and st.route_order = 4), '300615', 'Toko Kopi Tuku BP JGC', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 2'), 5, 'Toko Kopi Tuku Harapan Indah', 'harapan indah', '08:02:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 2') and st.route_order = 5), '271', 'Toko Kopi Tuku Harapan Indah', true) on conflict do nothing;
-- VAN 3 (depart: 4:25)
insert into public.tms_sla_route_profiles (client_id, group_id, code, name, departure_target_time, effective_from, status, source_file) values ((select id from public.tms_clients where code = 'TUKU'), (select id from public.tms_live_track_groups where lower(name) = 'cp'), 'VAN 3', 'VAN 3 CP Tuku', '4:25', '2026-09-29', 'Aktif', 'Plaan Rute Sabang + NSO BP JGC.xlsx') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 3'), 1, 'Toko Kopi Tuku Jatinegara', 'jatinegara', '04:59:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 3') and st.route_order = 1), '195837', 'Toko Kopi Tuku Jatinegara', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 3'), 2, 'Toko Kopi Tuku Pahlawan Revolusi', 'pahlawan revolusi', '05:46:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 3') and st.route_order = 2), '300613', 'Toko Kopi Tuku Pahlawan Revolusi', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 3'), 3, 'Toko Kopi Tuku Pulo asem', 'pulo asem', '06:12:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 3') and st.route_order = 3), '270', 'Toko Kopi Tuku Pulo asem', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 3'), 4, 'Toko Kopi Tuku Kota Bintang', 'kota bintang', '06:43:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 3') and st.route_order = 4), '154626', 'Toko Kopi Tuku Kota Bintang', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 3'), 5, 'Toko Kopi Tuku Bp galaxy', 'bp galaxy', '07:09:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 3') and st.route_order = 5), '274', 'Toko Kopi Tuku Bp galaxy', true) on conflict do nothing;
-- VAN 4 (depart: 4:41)
insert into public.tms_sla_route_profiles (client_id, group_id, code, name, departure_target_time, effective_from, status, source_file) values ((select id from public.tms_clients where code = 'TUKU'), (select id from public.tms_live_track_groups where lower(name) = 'cp'), 'VAN 4', 'VAN 4 CP Tuku', '4:41', '2026-09-29', 'Aktif', 'Plaan Rute Sabang + NSO BP JGC.xlsx') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 4'), 1, 'Toko Kopi Tuku Cibubur point', 'cibubur point', '04:59:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 4') and st.route_order = 1), '240298', 'Toko Kopi Tuku Cibubur point', true) on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 4') and st.route_order = 1), '6553', 'Toko Kopi Tuku Cibubur point', false) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 4'), 2, 'Toko Kopi Tuku Bp Sentul', 'bp sentul', '06:04:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 4') and st.route_order = 2), '12417', 'Toko Kopi Tuku Bp Sentul', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 4'), 3, 'Toko Kopi Tuku Bp Yasmin', 'bp yasmin', '06:23:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 4') and st.route_order = 3), '279', 'Toko Kopi Tuku Bp Yasmin', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 4'), 4, 'Toko Kopi Tuku Bp Ahmad Yani', 'bp ahmad yani', '06:46:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 4') and st.route_order = 4), '39137', 'Toko Kopi Tuku Bp Ahmad Yani', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 4'), 5, 'Toko Kopi Tuku Pajajaran Bogor', 'pajajaran bogor', '07:04:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 4') and st.route_order = 5), '25634', 'Toko Kopi Tuku Pajajaran Bogor', true) on conflict do nothing;
-- VAN 5 (depart: 4:38)
insert into public.tms_sla_route_profiles (client_id, group_id, code, name, departure_target_time, effective_from, status, source_file) values ((select id from public.tms_clients where code = 'TUKU'), (select id from public.tms_live_track_groups where lower(name) = 'cp'), 'VAN 5', 'VAN 5 CP Tuku', '4:38', '2026-09-29', 'Aktif', 'Plaan Rute Sabang + NSO BP JGC.xlsx') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 5'), 1, 'Toko kopi Tuku Karawaci', 'karawaci', '04:58:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 5') and st.route_order = 1), '25539', 'Toko kopi Tuku Karawaci', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 5'), 2, 'Toko Kopi Tuku Pasar lama', 'pasar lama', '05:34:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 5') and st.route_order = 2), '282', 'Toko Kopi Tuku Pasar lama', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 5'), 3, 'Toko Kopi Tuku Ciledug', 'ciledug', '06:23:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 5') and st.route_order = 3), '263', 'Toko Kopi Tuku Ciledug', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 5'), 4, 'Toko Kopi Tuku Joglo', 'joglo', '06:48:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 5') and st.route_order = 4), '6114', 'Toko Kopi Tuku Joglo', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 5'), 5, 'Toko Kopi Tuku Puri indah', 'puri indah', '07:16:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 5') and st.route_order = 5), '200783', 'Toko Kopi Tuku Puri indah', true) on conflict do nothing;
-- VAN 6 (depart: 4:51)
insert into public.tms_sla_route_profiles (client_id, group_id, code, name, departure_target_time, effective_from, status, source_file) values ((select id from public.tms_clients where code = 'TUKU'), (select id from public.tms_live_track_groups where lower(name) = 'cp'), 'VAN 6', 'VAN 6 CP Tuku', '4:51', '2026-09-29', 'Aktif', 'Plaan Rute Sabang + NSO BP JGC.xlsx') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6'), 1, 'Toko Kopi Tuku Commercial', 'commercial', '04:51:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6') and st.route_order = 1), '13005', 'Toko Kopi Tuku Commercial', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6'), 2, 'Toko Kopi Tuku Majid', 'majid', '05:08:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6') and st.route_order = 2), '264', 'Toko Kopi Tuku Majid', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6'), 3, 'Toko Kopi Tuku Cipete', 'cipete', '05:47:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6') and st.route_order = 3), '287', 'Toko Kopi Tuku Cipete', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6'), 4, 'Toko Kopi Tuku Kemang', 'kemang', '06:07:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6') and st.route_order = 4), '12418', 'Toko Kopi Tuku Kemang', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6'), 5, 'Toko Kopi Tuku Perdatam', 'perdatam', '06:33:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6') and st.route_order = 5), '43646', 'Toko Kopi Tuku Perdatam', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6'), 6, 'Toko Kopi Tuku Salihara', 'salihara', '06:59:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6') and st.route_order = 6), '9553', 'Toko Kopi Tuku Salihara', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6'), 7, 'Toko Kopi Tuku Bp Lenteng Agung', 'bp lenteng agung', '07:22:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 6') and st.route_order = 7), '5444', 'Toko Kopi Tuku Bp Lenteng Agung', true) on conflict do nothing;
-- VAN 7 (depart: 4:51)
insert into public.tms_sla_route_profiles (client_id, group_id, code, name, departure_target_time, effective_from, status, source_file) values ((select id from public.tms_clients where code = 'TUKU'), (select id from public.tms_live_track_groups where lower(name) = 'cp'), 'VAN 7', 'VAN 7 CP Tuku', '4:51', '2026-09-29', 'Aktif', 'Plaan Rute Sabang + NSO BP JGC.xlsx') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 7'), 1, 'Toko Kopi Tuku GBK', 'gbk', '05:00:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 7') and st.route_order = 1), '25468', 'Toko Kopi Tuku GBK', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 7'), 2, 'Toko Kopi Tuku Blok M', 'blok m', '05:59:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 7') and st.route_order = 2), '288', 'Toko Kopi Tuku Blok M', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 7'), 3, 'Toko Kopi Tuku Santa', 'santa', '06:17:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 7') and st.route_order = 3), '283', 'Toko Kopi Tuku Santa', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 7'), 4, 'Toko Kopi Tuku Karang Tengah', 'karang tengah', '06:54:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 7') and st.route_order = 4), '275', 'Toko Kopi Tuku Karang Tengah', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 7'), 5, 'Toko Kopi Tuku Cirendeu', 'cirendeu', '07:13:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 7') and st.route_order = 5), '208883', 'Toko Kopi Tuku Cirendeu', true) on conflict do nothing;
-- VAN 8 (depart: -)
insert into public.tms_sla_route_profiles (client_id, group_id, code, name, departure_target_time, effective_from, status, source_file) values ((select id from public.tms_clients where code = 'TUKU'), (select id from public.tms_live_track_groups where lower(name) = 'cp'), 'VAN 8', 'VAN 8 CP Tuku', null, '2026-09-29', 'Aktif', 'Plaan Rute Sabang + NSO BP JGC.xlsx') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 8'), 1, 'Toko Kopi Tuku Cinere', 'cinere', '04:55:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 8') and st.route_order = 1), '6649', 'Toko Kopi Tuku Cinere', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 8'), 2, 'Toko Kopi Tuku Ciganjur', 'ciganjur', '05:59:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 8') and st.route_order = 2), '276', 'Toko Kopi Tuku Ciganjur', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 8'), 3, 'Toko Kopi Tuku kelapa dua', 'kelapa dua', '06:34:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 8') and st.route_order = 3), '277', 'Toko Kopi Tuku kelapa dua', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 8'), 4, 'Toko Kopi Tuku Bp GDC', 'bp gdc', '06:58:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 8') and st.route_order = 4), '11428', 'Toko Kopi Tuku Bp GDC', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 8'), 5, 'Toko Kopi Tuku Pancoran mas', 'pancoran mas', '07:25:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 8') and st.route_order = 5), '10734', 'Toko Kopi Tuku Pancoran mas', true) on conflict do nothing;
-- VAN 9 (depart: -)
insert into public.tms_sla_route_profiles (client_id, group_id, code, name, departure_target_time, effective_from, status, source_file) values ((select id from public.tms_clients where code = 'TUKU'), (select id from public.tms_live_track_groups where lower(name) = 'cp'), 'VAN 9', 'VAN 9 CP Tuku', null, '2026-09-29', 'Aktif', 'Plaan Rute Sabang + NSO BP JGC.xlsx') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 9'), 1, 'Toko Kopi Tuku Dukuh Atas', 'dukuh atas', '05:05:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 9') and st.route_order = 1), '43690', 'Toko Kopi Tuku Dukuh Atas', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 9'), 2, 'Toko Kopi Tuku Karbela', 'karbela', '05:54:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 9') and st.route_order = 2), '300611', 'Toko Kopi Tuku Karbela', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 9'), 3, 'Toko Kopi Tuku Tebet', 'tebet', '06:14:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 9') and st.route_order = 3), '284', 'Toko Kopi Tuku Tebet', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 9'), 4, 'Toko Kopi Tuku Bukit Duri', 'bukit duri', '06:31:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 9') and st.route_order = 4), '11514', 'Toko Kopi Tuku Bukit Duri', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 9'), 5, 'Toko Kopi Tuku Bp Minangkabau', 'bp minangkabau', '06:51:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 9') and st.route_order = 5), '13033', 'Toko Kopi Tuku Bp Minangkabau', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 9'), 6, 'Toko Kopi Tuku Sabang', 'sabang', '07:25:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 9') and st.route_order = 6), '6552', 'Toko Kopi Tuku Sabang', true) on conflict do nothing;
-- VAN 10 (depart: -)
insert into public.tms_sla_route_profiles (client_id, group_id, code, name, departure_target_time, effective_from, status, source_file) values ((select id from public.tms_clients where code = 'TUKU'), (select id from public.tms_live_track_groups where lower(name) = 'cp'), 'VAN 10', 'VAN 10 CP Tuku', null, '2026-09-29', 'Aktif', 'Plaan Rute Sabang + NSO BP JGC.xlsx') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 10'), 1, 'Toko Kopi Tuku Kemanggisan', 'kemanggisan', '05:29:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 10') and st.route_order = 1), '289', 'Toko Kopi Tuku Kemanggisan', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 10'), 2, 'Toko Kopi Tuku JDC', 'jdc', '06:00:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 10') and st.route_order = 2), '38774', 'Toko Kopi Tuku JDC', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 10'), 3, 'Toko Kopi Tuku Bp Simprug', 'bp simprug', '06:34:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 10') and st.route_order = 3), '4950', 'Toko Kopi Tuku Bp Simprug', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 10'), 4, 'Toko Kopi Tuku Bintaro', 'bintaro', '07:06:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 10') and st.route_order = 4), '262', 'Toko Kopi Tuku Bintaro', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 10'), 5, 'Toko Kopi Tuku Pondok Indah', 'pondok indah', '07:54:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 10') and st.route_order = 5), '9579', 'Toko Kopi Tuku Pondok Indah', true) on conflict do nothing;
-- VAN 11 (depart: -)
insert into public.tms_sla_route_profiles (client_id, group_id, code, name, departure_target_time, effective_from, status, source_file) values ((select id from public.tms_clients where code = 'TUKU'), (select id from public.tms_live_track_groups where lower(name) = 'cp'), 'VAN 11', 'VAN 11 CP Tuku', null, '2026-09-29', 'Aktif', 'Plaan Rute Sabang + NSO BP JGC.xlsx') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 11'), 1, 'Toko kopi Tuku Pondok Aren', 'pondok aren', '05:03:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 11') and st.route_order = 1), '30532', 'Toko kopi Tuku Pondok Aren', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 11'), 2, 'Toko Kopi Tuku Bp Bintaro', 'bp bintaro', '05:41:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 11') and st.route_order = 2), '265', 'Toko Kopi Tuku Bp Bintaro', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 11'), 3, 'Toko Kopi Tuku Graha raya', 'graha raya', '06:17:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 11') and st.route_order = 3), '280', 'Toko Kopi Tuku Graha raya', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 11'), 4, 'Toko Kopi Tuku Pasar 8', 'pasar 8', '06:50:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 11') and st.route_order = 4), '281', 'Toko Kopi Tuku Pasar 8', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 11'), 5, 'toko Kopi tuku Bp Serpong', 'bp serpong', '07:22:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 11') and st.route_order = 5), '266', 'toko Kopi tuku Bp Serpong', true) on conflict do nothing;
-- VAN 12 (depart: -)
insert into public.tms_sla_route_profiles (client_id, group_id, code, name, departure_target_time, effective_from, status, source_file) values ((select id from public.tms_clients where code = 'TUKU'), (select id from public.tms_live_track_groups where lower(name) = 'cp'), 'VAN 12', 'VAN 12 CP Tuku', null, '2026-09-29', 'Aktif', 'Plaan Rute Sabang + NSO BP JGC.xlsx') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 12'), 1, 'Toko Kopi tuku BSD', 'bsd', '05:12:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 12') and st.route_order = 1), '267', 'Toko Kopi tuku BSD', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 12'), 2, 'Toko Kopi Tuku BSD Online', 'bsd online', '05:24:00') on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 12'), 3, 'Toko Kopi Tuku The Icon BSD', 'the icon bsd', '06:13:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 12') and st.route_order = 3), '17005', 'Toko Kopi Tuku The Icon BSD', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 12'), 4, 'Toko Kopi Tuku Pamulang', 'pamulang', '06:57:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 12') and st.route_order = 4), '269', 'Toko Kopi Tuku Pamulang', true) on conflict do nothing;
insert into public.tms_sla_route_stops (profile_id, route_order, store_name, store_name_key, target_time) values ((select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 12'), 5, 'Toko Kopi Tuku CitraLake', 'citralake', '07:25:00') on conflict do nothing;
insert into public.tms_sla_route_stop_addresses (route_stop_id, vendor_address_id, store_name_snapshot, is_primary) values ((select st.id from public.tms_sla_route_stops st where st.profile_id = (select p.id from public.tms_sla_route_profiles p where p.group_id = (select id from public.tms_live_track_groups where lower(name) = 'cp') and p.code = 'VAN 12') and st.route_order = 5), '275040', 'Toko Kopi Tuku CitraLake', true) on conflict do nothing;

-- Hitung snapshot SLA untuk histori sejak 2026-09-29.
select public.tms_sla_backfill('2026-09-29');
