-- ────────────────────────────────────────────
-- TABLE: division_locations
-- Titik koordinat absen per divisi
-- Satu divisi bisa punya beberapa titik lokasi
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.division_locations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  division_id integer NOT NULL REFERENCES public.divisions(id) ON DELETE CASCADE,
  nama varchar(100) NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  radius integer NOT NULL DEFAULT 100,
  status varchar(20) NOT NULL DEFAULT 'Aktif'::varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT division_locations_status_check CHECK (
    status::text = ANY (ARRAY['Aktif', 'Tidak Aktif']::text[])
  ),
  CONSTRAINT division_locations_radius_check CHECK (radius > 0)
);

CREATE INDEX IF NOT EXISTS idx_division_locations_division ON public.division_locations USING btree (division_id);

CREATE TRIGGER trg_division_locations_updated_at
  BEFORE UPDATE ON public.division_locations
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

ALTER TABLE public.division_locations ENABLE ROW LEVEL SECURITY;

CREATE POLICY allow_all_division_locations ON public.division_locations
  FOR ALL TO public
  USING (true) WITH CHECK (true);

-- ────────────────────────────────────────────
-- TABLE: division_schedules
-- Jam kerja per divisi (1 jadwal per divisi)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.division_schedules (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  division_id integer NOT NULL UNIQUE REFERENCES public.divisions(id) ON DELETE CASCADE,
  jam_masuk time NOT NULL DEFAULT '08:00',
  jam_pulang time NOT NULL DEFAULT '17:00',
  toleransi_menit integer NOT NULL DEFAULT 15,
  status varchar(20) NOT NULL DEFAULT 'Aktif'::varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT division_schedules_status_check CHECK (
    status::text = ANY (ARRAY['Aktif', 'Tidak Aktif']::text[])
  ),
  CONSTRAINT division_schedules_toleransi_check CHECK (toleransi_menit >= 0)
);

CREATE TRIGGER trg_division_schedules_updated_at
  BEFORE UPDATE ON public.division_schedules
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

ALTER TABLE public.division_schedules ENABLE ROW LEVEL SECURITY;

CREATE POLICY allow_all_division_schedules ON public.division_schedules
  FOR ALL TO public
  USING (true) WITH CHECK (true);
