-- ============================================================
-- BASELINE MIGRATION
-- Generated from existing hrm-system Supabase schema
-- Date: 2026-04-21 (project creation date)
-- ============================================================

-- ────────────────────────────────────────────
-- 1. FUNCTION: update_updated_at
-- Auto-update updated_at column on row update
-- ────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

-- ────────────────────────────────────────────
-- 2. TABLE: levels
-- Tingkatan/level jabatan
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.levels (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama varchar(100) NOT NULL,
  urutan integer NOT NULL DEFAULT 1,
  status varchar(20) NOT NULL DEFAULT 'Aktif'::varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT levels_status_check CHECK (
    status::text = ANY (ARRAY['Aktif', 'Tidak Aktif']::text[])
  )
);

CREATE INDEX IF NOT EXISTS idx_levels_urutan ON public.levels USING btree (urutan);

-- Trigger: auto-update updated_at
CREATE TRIGGER trg_levels_updated_at
  BEFORE UPDATE ON public.levels
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

-- ────────────────────────────────────────────
-- 3. TABLE: jabatan
-- Posisi/jabatan pegawai
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.jabatan (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama varchar(200) NOT NULL,
  deskripsi text,
  level_id integer REFERENCES public.levels(id),
  status varchar(20) NOT NULL DEFAULT 'Aktif'::varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT jabatan_status_check CHECK (
    status::text = ANY (ARRAY['Aktif', 'Tidak Aktif']::text[])
  )
);

CREATE INDEX IF NOT EXISTS idx_jabatan_level ON public.jabatan USING btree (level_id);

-- Trigger: auto-update updated_at
CREATE TRIGGER trg_jabatan_updated_at
  BEFORE UPDATE ON public.jabatan
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

-- ────────────────────────────────────────────
-- 4. TABLE: pegawai
-- Data karyawan/pegawai
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pegawai (
  id varchar(20) PRIMARY KEY,
  nama varchar(200) NOT NULL,
  jenis_kelamin varchar(20) NOT NULL,
  agama varchar(20) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'Aktif'::varchar,
  no_ktp varchar(16) NOT NULL,
  tempat_lahir varchar(100) NOT NULL,
  tanggal_lahir date NOT NULL,
  alamat_ktp text NOT NULL,
  alamat_domisili text NOT NULL,
  no_telp varchar(20) NOT NULL,
  tanggal_bergabung date NOT NULL,
  jabatan_id integer REFERENCES public.jabatan(id),
  status_pernikahan varchar(20) NOT NULL DEFAULT 'Belum Menikah'::varchar,
  nama_pasangan varchar(200),
  jumlah_anak integer NOT NULL DEFAULT 0,
  foto_ktp text,
  foto_diri text,
  no_bpjs_kesehatan varchar(20),
  no_bpjs_ketenagakerjaan varchar(20),
  foto_sim text,
  no_rekening varchar(30) NOT NULL,
  bank varchar(50) NOT NULL,
  nama_rekening varchar(200) NOT NULL,
  kartu_keluarga text,
  tanggal_mulai_pkwt date,
  tanggal_berakhir_pkwt date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pegawai_jenis_kelamin_check CHECK (
    jenis_kelamin::text = ANY (ARRAY['Laki-laki', 'Perempuan']::text[])
  ),
  CONSTRAINT pegawai_agama_check CHECK (
    agama::text = ANY (ARRAY['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu']::text[])
  ),
  CONSTRAINT pegawai_status_check CHECK (
    status::text = ANY (ARRAY['Aktif', 'Tidak Aktif', 'Cuti']::text[])
  ),
  CONSTRAINT pegawai_status_pernikahan_check CHECK (
    status_pernikahan::text = ANY (ARRAY['Belum Menikah', 'Menikah', 'Cerai']::text[])
  )
);

CREATE INDEX IF NOT EXISTS idx_pegawai_jabatan ON public.pegawai USING btree (jabatan_id);
CREATE INDEX IF NOT EXISTS idx_pegawai_status ON public.pegawai USING btree (status);

-- Trigger: auto-update updated_at
CREATE TRIGGER trg_pegawai_updated_at
  BEFORE UPDATE ON public.pegawai
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

-- ────────────────────────────────────────────
-- 5. ROW LEVEL SECURITY (RLS)
-- ────────────────────────────────────────────

-- Enable RLS on all tables
ALTER TABLE public.levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jabatan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pegawai ENABLE ROW LEVEL SECURITY;

-- Policies (currently permissive - should be tightened for production)
CREATE POLICY allow_all_levels ON public.levels
  FOR ALL TO public
  USING (true) WITH CHECK (true);

CREATE POLICY allow_all_jabatan ON public.jabatan
  FOR ALL TO public
  USING (true) WITH CHECK (true);

CREATE POLICY allow_all_pegawai ON public.pegawai
  FOR ALL TO public
  USING (true) WITH CHECK (true);

-- ────────────────────────────────────────────
-- 6. STORAGE: pegawai-docs bucket
-- Bucket untuk dokumen pegawai (KTP, foto, SIM, KK)
-- ────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('pegawai-docs', 'pegawai-docs', true, null, null)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for pegawai-docs bucket
CREATE POLICY allow_public_select ON storage.objects
  FOR SELECT TO public
  USING (bucket_id = 'pegawai-docs');

CREATE POLICY allow_public_insert ON storage.objects
  FOR INSERT TO public
  WITH CHECK (bucket_id = 'pegawai-docs');

CREATE POLICY allow_public_update ON storage.objects
  FOR UPDATE TO public
  USING (bucket_id = 'pegawai-docs');

CREATE POLICY allow_public_delete ON storage.objects
  FOR DELETE TO public
  USING (bucket_id = 'pegawai-docs');
