-- ────────────────────────────────────────────
-- TABLE: banks
-- Master data bank untuk dropdown pegawai
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.banks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama varchar(100) NOT NULL,
  kode varchar(10),
  status varchar(20) NOT NULL DEFAULT 'Aktif'::varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT banks_status_check CHECK (
    status::text = ANY (ARRAY['Aktif', 'Tidak Aktif']::text[])
  )
);

-- Trigger: auto-update updated_at
CREATE TRIGGER trg_banks_updated_at
  BEFORE UPDATE ON public.banks
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

-- Enable RLS
ALTER TABLE public.banks ENABLE ROW LEVEL SECURITY;

-- Policy
CREATE POLICY allow_all_banks ON public.banks
  FOR ALL TO public
  USING (true) WITH CHECK (true);

-- Seed data: bank-bank utama Indonesia
INSERT INTO public.banks (nama, kode) VALUES
  ('BCA', '014'),
  ('Mandiri', '008'),
  ('BNI', '009'),
  ('BRI', '002'),
  ('BSI', '451'),
  ('CIMB Niaga', '022'),
  ('Danamon', '011'),
  ('Permata', '013'),
  ('OCBC NISP', '028'),
  ('Panin', '019'),
  ('Maybank', '016'),
  ('BTN', '200'),
  ('Mega', '426'),
  ('Sinarmas', '153'),
  ('Commonwealth', '950'),
  ('HSBC', '087'),
  ('UOB', '023'),
  ('BTPN', '213'),
  ('Jago', '542'),
  ('Sea Bank', '535'),
  ('Bank Neo Commerce', '490'),
  ('Allo Bank', '567'),
  ('Blu by BCA Digital', '501');
