import { describe, it, expect } from "vitest";
import {
  MIN_DATE,
  PAGE_SIZE,
  SUMMARY_PAGE_SIZE,
  SUMMARY_CUT_OFF_DAY,
  HOLIDAY_LIST_PAGE_SIZE,
  HOLIDAY_DETAIL_PAGE_SIZE,
  DEFAULT_DENDA_PER_MENIT,
  DEFAULT_BATAS_MENIT,
  DEFAULT_DENDA_MAKSIMUM,
  DEFAULT_DENDA_ALPHA,
  DAY_NAMES,
  DAY_SHORT,
  AUTO_NOTES,
  AUTO_NOTE_PREFIXES,
  isAutoGeneratedNote,
  ALASAN_MANUAL_OPTIONS,
  HOLIDAY_COLORS,
} from "../lib/attendance-constants";

describe("attendance-constants", () => {
  describe("page sizes & limits", () => {
    it("MIN_DATE uses ISO date format YYYY-MM-DD", () => {
      expect(MIN_DATE).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    });

    it("PAGE_SIZE & SUMMARY_PAGE_SIZE adalah 15", () => {
      expect(PAGE_SIZE).toBe(15);
      expect(SUMMARY_PAGE_SIZE).toBe(15);
    });

    it("SUMMARY_CUT_OFF_DAY adalah 8 (periode cutoff 8-7)", () => {
      expect(SUMMARY_CUT_OFF_DAY).toBe(8);
    });

    it("HOLIDAY_LIST_PAGE_SIZE & HOLIDAY_DETAIL_PAGE_SIZE positive", () => {
      expect(HOLIDAY_LIST_PAGE_SIZE).toBeGreaterThan(0);
      expect(HOLIDAY_DETAIL_PAGE_SIZE).toBeGreaterThan(0);
    });
  });

  describe("default penalty values", () => {
    it("default denda per menit adalah 3000", () => {
      expect(DEFAULT_DENDA_PER_MENIT).toBe(3000);
    });

    it("default batas menit adalah 20", () => {
      expect(DEFAULT_BATAS_MENIT).toBe(20);
    });

    it("default denda maksimum adalah 60000", () => {
      expect(DEFAULT_DENDA_MAKSIMUM).toBe(60000);
    });

    it("default denda alpha adalah 100000", () => {
      expect(DEFAULT_DENDA_ALPHA).toBe(100000);
    });
  });

  describe("day name arrays", () => {
    it("DAY_NAMES memiliki 7 hari sesuai urutan Minggu-Sabtu", () => {
      expect(DAY_NAMES).toHaveLength(7);
      expect(DAY_NAMES[0]).toBe("Minggu");
      expect(DAY_NAMES[6]).toBe("Sabtu");
    });

    it("DAY_SHORT memiliki 7 hari singkat", () => {
      expect(DAY_SHORT).toHaveLength(7);
      expect(DAY_SHORT[0]).toBe("Min");
      expect(DAY_SHORT[6]).toBe("Sab");
    });

    it("DAY_SHORT dan DAY_NAMES urutan index konsisten", () => {
      const longMap: Record<string, number> = {
        Minggu: 0, Senin: 1, Selasa: 2, Rabu: 3, Kamis: 4, Jumat: 5, Sabtu: 6,
      };
      const shortMap: Record<string, number> = {
        Min: 0, Sen: 1, Sel: 2, Rab: 3, Kam: 4, Jum: 5, Sab: 6,
      };
      DAY_NAMES.forEach((n, i) => {
        expect(shortMap[DAY_SHORT[i]]).toBe(longMap[n]);
      });
    });
  });

  describe("AUTO_NOTES builders", () => {
    it("HARI_LIBUR deterministik", () => {
      expect(AUTO_NOTES.HARI_LIBUR).toBe("Hari libur");
    });

    it("LIBUR_NASIONAL format dengan nama holiday", () => {
      expect(AUTO_NOTES.LIBUR_NASIONAL("Idul Fitri")).toBe("Libur nasional: Idul Fitri");
      expect(AUTO_NOTES.LIBUR_NASIONAL("Natal 2026")).toBe("Libur nasional: Natal 2026");
    });

    it("ALPHA catatan lengkap dengan suffix", () => {
      expect(AUTO_NOTES.ALPHA).toBe("Alpha otomatis — tidak ada record kehadiran");
    });

    it("CUTI builder menghasilkan format konsisten", () => {
      expect(AUTO_NOTES.CUTI("Izin")).toBe("Izin otomatis — sudah disetujui");
      expect(AUTO_NOTES.CUTI("Sakit")).toBe("Sakit otomatis — sudah disetujui");
      expect(AUTO_NOTES.CUTI("Cuti")).toBe("Cuti otomatis — sudah disetujui");
    });
  });

  describe("AUTO_NOTE_PREFIXES", () => {
    it("prefixes match substring dari AUTO_NOTES builders", () => {
      expect(AUTO_NOTES.LIBUR_NASIONAL("Test").startsWith(AUTO_NOTE_PREFIXES.LIBUR_NASIONAL)).toBe(true);
      expect(AUTO_NOTES.ALPHA.startsWith(AUTO_NOTE_PREFIXES.ALPHA)).toBe(true);
    });
  });

  describe("isAutoGeneratedNote", () => {
    it("return false untuk null/undefined/empty", () => {
      expect(isAutoGeneratedNote(null)).toBe(false);
      expect(isAutoGeneratedNote(undefined)).toBe(false);
      expect(isAutoGeneratedNote("")).toBe(false);
    });

    it("return true untuk AUTO_NOTES.HARI_LIBUR exact", () => {
      expect(isAutoGeneratedNote("Hari libur")).toBe(true);
    });

    it("return true untuk catatan Libur nasional", () => {
      expect(isAutoGeneratedNote("Libur nasional: Natal")).toBe(true);
      expect(isAutoGeneratedNote("Libur nasional: ")).toBe(true);
    });

    it("return true untuk catatan Alpha otomatis", () => {
      expect(isAutoGeneratedNote("Alpha otomatis — tidak ada record kehadiran")).toBe(true);
      expect(isAutoGeneratedNote("Alpha otomatis")).toBe(true);
    });

    it("return false untuk catatan manual", () => {
      expect(isAutoGeneratedNote("Sakit demam tinggi")).toBe(false);
      expect(isAutoGeneratedNote("Izin keluarga")).toBe(false);
      expect(isAutoGeneratedNote(null)).toBe(false);
    });

    it("return false untuk catatan AUTO_NOTES.CUTI (Cuti/Izin/Sakit — bukan libur/alpha)", () => {
      // Penting: isAutoGeneratedNote saat ini hanya deteksi Libur & Alpha.
      // Cuti/Izin/Sakit yang auto-generated dari leave_requests TIDAK di-overwrite
      // oleh syncHoliday — boleh di-handle manual via leave request, bukan catatan sistem.
      expect(isAutoGeneratedNote("Izin otomatis — sudah disetujui")).toBe(false);
    });
  });

  describe("ALASAN_MANUAL_OPTIONS", () => {
    it("memiliki minimal 5 opsi", () => {
      expect(ALASAN_MANUAL_OPTIONS.length).toBeGreaterThanOrEqual(5);
    });

    it("include 'Lainnya' untuk input custom", () => {
      expect(ALASAN_MANUAL_OPTIONS).toContain("Lainnya");
    });

    it("semua entries non-empty strings", () => {
      ALASAN_MANUAL_OPTIONS.forEach((a) => {
        expect(typeof a).toBe("string");
        expect(a.length).toBeGreaterThan(0);
      });
    });
  });

  describe("HOLIDAY_COLORS", () => {
    it("memiliki 3 kategori: Nasional, Cuti Bersama, Spesial", () => {
      expect(Object.keys(HOLIDAY_COLORS).sort()).toEqual(["Cuti Bersama", "Nasional", "Spesial"]);
    });

    it("semua warna berformat hex", () => {
      Object.values(HOLIDAY_COLORS).forEach((c) => {
        expect(c).toMatch(/^#[0-9a-fA-F]{6}$/);
      });
    });
  });
});
