/**
 * Konstanta domain absensi.
 *
 * File ini WAJIB pure (tanpa dependency React/Supabase) agar bisa di-import
 * dari Server Components, hooks, maupun utility functions.
 */

/** Tanggal paling awal yang bisa dipilih user di date picker. */
export const MIN_DATE = "2026-05-08";

/** Ukuran halaman tabel absen harian. */
export const PAGE_SIZE = 15;

/** Ukuran halaman tabel ringkasan per pegawai. */
export const SUMMARY_PAGE_SIZE = 15;

/** Tanggal cutoff periode ringkasan (tanggal 8 bulan ini s/d tanggal 7 bulan berikutnya). */
export const SUMMARY_CUT_OFF_DAY = 8;

/** Ukuran halaman list hari libur di tab Atur Libur. */
export const HOLIDAY_LIST_PAGE_SIZE = 10;

/** Ukuran halaman list pegawai di modal detail hari libur. */
export const HOLIDAY_DETAIL_PAGE_SIZE = 15;

/** Page size pagination untuk kalender (server-side, internal). */
export const CALENDAR_FETCH_PAGE_SIZE = 1000;

/** Page size pagination untuk ringkasan (server-side, internal). */
export const SUMMARY_FETCH_PAGE_SIZE = 1000;

/** Default denda per menit (fallback kalau division penalty tidak ditemukan). */
export const DEFAULT_DENDA_PER_MENIT = 3000;

/** Default batas menit telat. */
export const DEFAULT_BATAS_MENIT = 20;

/** Default denda maksimum. */
export const DEFAULT_DENDA_MAKSIMUM = 60000;

/** Default denda alpha. */
export const DEFAULT_DENDA_ALPHA = 100000;

/** Nama hari dalam bahasa Indonesia (panjang). */
export const DAY_NAMES = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"] as const;

/** Nama hari singkat. */
export const DAY_SHORT = ["Min", "Sen", "Sel", "Rab", "Kam", "Jum", "Sab"] as const;

/**
 * Format catatan untuk record yang di-generate oleh sistem (bukan admin manual).
 * Penting: string di sini digunakan sebagai marker untuk deteksi record auto-generated
 * oleh `isAutoGeneratedCatatan()`. JANGAN ubah nilai literal tanpa update detektor.
 */
export const AUTO_NOTES = {
  /** Catatan untuk record Libur yang auto-generated dari jadwal mingguan. */
  HARI_LIBUR: "Hari libur",
  /** Builder catatan untuk record Libur yang auto-generated dari public_holidays. */
  LIBUR_NASIONAL: (nama: string) => `Libur nasional: ${nama}`,
  /** Catatan untuk record Alpha yang auto-generated (tidak ada kehadiran & bukan hari libur). */
  ALPHA: "Alpha otomatis — tidak ada record kehadiran",
  /** Builder catatan untuk record cuti/izin/sakit yang auto-generated dari leave_requests approved. */
  CUTI: (jenis: string) => `${jenis} otomatis — sudah disetujui`,
} as const;

/**
 * Prefix untuk substring-matching catatan auto-generated.
 * Pakai ini untuk cek apakah catatan dimulai dengan pola sistem
 * (mis. saat menangani legacy data yang punya suffix berbeda).
 */
export const AUTO_NOTE_PREFIXES = {
  LIBUR_NASIONAL: "Libur nasional:",
  ALPHA: "Alpha otomatis",
  CUTI_SUFFIX: " otomatis — sudah disetujui",
} as const;

/**
 * Deteksi apakah catatan termasuk auto-generated oleh sistem.
 * Return true untuk pola `AUTO_NOTES.*` maupun legacy dengan suffix berbeda.
 */
export function isAutoGeneratedNote(catatan: string | null | undefined): boolean {
  if (!catatan) return false;
  return (
    catatan === AUTO_NOTES.HARI_LIBUR ||
    catatan.startsWith(AUTO_NOTE_PREFIXES.LIBUR_NASIONAL) ||
    catatan.startsWith(AUTO_NOTE_PREFIXES.ALPHA)
  );
}

/**
 * Daftar alasan input manual absensi (wajib dipilih di form input/edit).
 * Alasan ini disimpan di kolom `alasan_manual` dan di-flag `is_manual = true`.
 */
export const ALASAN_MANUAL_OPTIONS = [
  "Lupa ID Card",
  "HP Rusak/Mati",
  "Aplikasi Error",
  "Tidak Ada Sinyal",
  "ID Card Hilang",
  "Baterai HP Habis",
  "Lainnya",
] as const;

export type AlasanManual = (typeof ALASAN_MANUAL_OPTIONS)[number];

/** Warna kategori hari libur (untuk badge & kalender). */
export const HOLIDAY_COLORS: Record<"Nasional" | "Cuti Bersama" | "Spesial", string> = {
  Nasional: "#3b82f6",
  "Cuti Bersama": "#f59e0b",
  Spesial: "#8b5cf6",
};
